/* ================== GIÁO TRÌNH HSK 3 — 300 từ mới chính thức (HSK 2.0), chia theo 20 bài của sách HSK标准教程 3 ================== */
const LESSONS = [
 {zh:"周末你有什么打算？", vi:"Cuối tuần bạn có dự định gì?", words:[
   ["周末","zhōumò","cuối tuần"],["打算","dǎsuan","dự định"],["跟","gēn","với, cùng"],["一直","yìzhí","luôn, suốt; thẳng"],["游戏","yóuxì","trò chơi"],["作业","zuòyè","bài tập về nhà"],["着急","zháojí","sốt ruột, vội"],["复习","fùxí","ôn tập"],["北方","běifāng","miền Bắc, phương Bắc"],["南","nán","phía nam"],["面包","miànbāo","bánh mì"],["带","dài","mang, dẫn theo"],["地图","dìtú","bản đồ"],["搬","bān","chuyển, dọn"],["爬山","pá shān","leo núi"]],
  sents:[{t:["周末","你","有","什么","打算"],z:"周末你有什么打算？",p:"Zhōumò nǐ yǒu shénme dǎsuàn?",v:"Cuối tuần bạn có dự định gì?"},{t:["我","打算","跟","朋友","去","爬山"],z:"我打算跟朋友去爬山。",p:"Wǒ dǎsuàn gēn péngyou qù pá shān.",v:"Mình định đi leo núi với bạn."},{t:["你","别","着急","我","一直","在","等","你"],z:"你别着急，我一直在等你。",p:"Nǐ bié zháojí, wǒ yìzhí zài děng nǐ.",v:"Bạn đừng sốt ruột, mình vẫn đang đợi bạn."},{t:["你","带","地图","了","吗"],z:"你带地图了吗？",p:"Nǐ dài dìtú le ma?",v:"Bạn mang bản đồ chưa?"}],
  write:["周","带"]},
 {zh:"他什么时候回来？", vi:"Khi nào anh ấy về?", words:[
   ["办公室","bàngōngshì","văn phòng"],["会议","huìyì","cuộc họp"],["经理","jīnglǐ","giám đốc, quản lý"],["同事","tóngshì","đồng nghiệp"],["刚才","gāngcái","vừa nãy"],["电子邮件","diànzǐ yóujiàn","email, thư điện tử"],["离开","líkāi","rời khỏi"],["马上","mǎshàng","ngay lập tức"],["一会儿","yíhuìr","một lát"],["司机","sījī","tài xế"],["接","jiē","đón; nghe (máy)"],["起飞","qǐfēi","cất cánh"],["迟到","chídào","đến muộn"],["请假","qǐngjià","xin nghỉ"],["还","huán","trả lại"]],
  sents:[{t:["经理","什么","时候","回","来"],z:"经理什么时候回来？",p:"Jīnglǐ shénme shíhou huílai?",v:"Khi nào giám đốc về?"},{t:["他","刚才","离开","办公室","了"],z:"他刚才离开办公室了。",p:"Tā gāngcái líkāi bàngōngshì le.",v:"Anh ấy vừa rời văn phòng."},{t:["会议","马上","就","要","开始","了"],z:"会议马上就要开始了。",p:"Huìyì mǎshàng jiù yào kāishǐ le.",v:"Cuộc họp sắp bắt đầu rồi."},{t:["司机","去","机场","接","经理","了"],z:"司机去机场接经理了。",p:"Sījī qù jīchǎng jiē jīnglǐ le.",v:"Tài xế ra sân bay đón giám đốc rồi."}],
  write:["办","接"]},
 {zh:"桌子上放着很多饮料", vi:"Trên bàn bày nhiều đồ uống", words:[
   ["放","fàng","đặt, để"],["饮料","yǐnliào","đồ uống"],["啤酒","píjiǔ","bia"],["瓶子","píngzi","cái chai"],["盘子","pánzi","cái đĩa"],["碗","wǎn","cái bát"],["筷子","kuàizi","đũa"],["蛋糕","dàngāo","bánh ngọt, bánh kem"],["香蕉","xiāngjiāo","chuối"],["冰箱","bīngxiāng","tủ lạnh"],["菜单","càidān","thực đơn"],["甜","tián","ngọt"],["尝","cháng","nếm"],["饿","è","đói"],["饱","bǎo","no"]],
  sents:[{t:["桌子","上","放","着","很","多","饮料"],z:"桌子上放着很多饮料。",p:"Zhuōzi shang fàng zhe hěn duō yǐnliào.",v:"Trên bàn bày rất nhiều đồ uống."},{t:["冰箱","里","有","啤酒","和","蛋糕"],z:"冰箱里有啤酒和蛋糕。",p:"Bīngxiāng li yǒu píjiǔ hé dàngāo.",v:"Trong tủ lạnh có bia và bánh kem."},{t:["你","尝","一下","这","个","蛋糕","很","甜"],z:"你尝一下，这个蛋糕很甜。",p:"Nǐ cháng yíxià, zhè ge dàngāo hěn tián.",v:"Bạn nếm thử đi, bánh này rất ngọt."},{t:["我","饿","了","我们","看","看","菜单","吧"],z:"我饿了，我们看看菜单吧。",p:"Wǒ è le, wǒmen kànkan càidān ba.",v:"Mình đói rồi, xem thực đơn đi."}],
  write:["放","饱"]},
 {zh:"她总是笑着跟客人说话", vi:"Cô ấy luôn tươi cười nói chuyện với khách", words:[
   ["总是","zǒngshì","luôn luôn"],["客人","kèrén","khách"],["热情","rèqíng","nhiệt tình"],["欢迎","huānyíng","chào mừng"],["阿姨","āyí","cô, dì"],["叔叔","shūshu","chú"],["邻居","línjū","hàng xóm"],["年轻","niánqīng","trẻ"],["可爱","kě'ài","dễ thương"],["照片","zhàopiàn","bức ảnh"],["照相机","zhàoxiàngjī","máy ảnh"],["像","xiàng","giống"],["头发","tóufa","tóc"],["个子","gèzi","vóc dáng, chiều cao"],["矮","ǎi","thấp, lùn"]],
  sents:[{t:["她","总是","笑","着","跟","客人","说话"],z:"她总是笑着跟客人说话。",p:"Tā zǒngshì xiào zhe gēn kèrén shuōhuà.",v:"Cô ấy luôn tươi cười nói chuyện với khách."},{t:["我","的","邻居","阿姨","很","热情"],z:"我的邻居阿姨很热情。",p:"Wǒ de línjū āyí hěn rèqíng.",v:"Cô hàng xóm của mình rất nhiệt tình."},{t:["照片","上","的","人","是","你","叔叔","吗"],z:"照片上的人是你叔叔吗？",p:"Zhàopiàn shang de rén shì nǐ shūshu ma?",v:"Người trong ảnh là chú bạn à?"},{t:["你","女儿","真","可爱","很","像","你"],z:"你女儿真可爱，很像你。",p:"Nǐ nǚ'ér zhēn kě'ài, hěn xiàng nǐ.",v:"Con gái bạn thật dễ thương, rất giống bạn."}],
  write:["客","欢"]},
 {zh:"我最近越来越胖了", vi:"Dạo này tôi ngày càng béo", words:[
   ["最近","zuìjìn","gần đây"],["越","yuè","càng"],["胖","pàng","béo"],["瘦","shòu","gầy"],["公斤","gōngjīn","ki-lô-gam"],["锻炼","duànliàn","rèn luyện, tập thể dục"],["健康","jiànkāng","khoẻ mạnh"],["体育","tǐyù","thể dục thể thao"],["鼻子","bízi","mũi"],["耳朵","ěrduo","tai"],["嘴","zuǐ","miệng"],["脸","liǎn","mặt, khuôn mặt"],["腿","tuǐ","chân (cẳng chân)"],["疼","téng","đau"],["脚","jiǎo","bàn chân"]],
  sents:[{t:["我","最近","越","来","越","胖","了"],z:"我最近越来越胖了。",p:"Wǒ zuìjìn yuè lái yuè pàng le.",v:"Dạo này mình ngày càng béo."},{t:["你","瘦","了","三","公斤","吗"],z:"你瘦了三公斤吗？",p:"Nǐ shòu le sān gōngjīn ma?",v:"Bạn gầy đi 3 cân à?"},{t:["他","每","个","星期","都","锻炼","身体"],z:"他每个星期都锻炼身体。",p:"Tā měi ge xīngqī dōu duànliàn shēntǐ.",v:"Tuần nào anh ấy cũng tập thể dục."},{t:["我","的","腿","很","疼"],z:"我的腿很疼。",p:"Wǒ de tuǐ hěn téng.",v:"Chân mình đau quá."}],
  write:["胖","瘦"]},
 {zh:"怎么突然找不到了？", vi:"Sao tự nhiên tìm không thấy?", words:[
   ["突然","tūrán","đột nhiên"],["记得","jìde","nhớ"],["忘记","wàngjì","quên"],["帽子","màozi","mũ"],["伞","sǎn","ô, dù"],["包","bāo","túi, cặp"],["信用卡","xìnyòngkǎ","thẻ tín dụng"],["皮鞋","píxié","giày da"],["裤子","kùzi","quần"],["裙子","qúnzi","váy"],["衬衫","chènshān","áo sơ mi"],["双","shuāng","đôi"],["条","tiáo","(lượng từ: vật dài) chiếc, con"],["换","huàn","đổi, thay"],["旧","jiù","cũ"]],
  sents:[{t:["我","的","伞","怎么","突然","找","不","到","了"],z:"我的伞怎么突然找不到了？",p:"Wǒ de sǎn zěnme tūrán zhǎo bu dào le?",v:"Sao ô của mình tự nhiên tìm không thấy?"},{t:["你","记得","信用卡","放","在","哪儿","吗"],z:"你记得信用卡放在哪儿吗？",p:"Nǐ jìde xìnyòngkǎ fàng zài nǎr ma?",v:"Bạn có nhớ để thẻ tín dụng ở đâu không?"},{t:["我","忘记","带","包","了"],z:"我忘记带包了。",p:"Wǒ wàngjì dài bāo le.",v:"Mình quên mang túi rồi."},{t:["这","条","裤子","太","旧","了","换","一","条","吧"],z:"这条裤子太旧了，换一条吧。",p:"Zhè tiáo kùzi tài jiù le, huàn yì tiáo ba.",v:"Quần này cũ quá, đổi cái khác đi."}],
  write:["突","换"]},
 {zh:"我跟她都认识五年了", vi:"Tôi quen cô ấy đã 5 năm", words:[
   ["结婚","jiéhūn","kết hôn"],["见面","jiànmiàn","gặp mặt"],["久","jiǔ","lâu"],["关系","guānxi","quan hệ"],["了解","liǎojiě","hiểu rõ, tìm hiểu"],["奶奶","nǎinai","bà nội"],["爷爷","yéye","ông nội"],["自己","zìjǐ","tự mình, bản thân"],["聊天","liáotiān","trò chuyện"],["节日","jiérì","ngày lễ"],["礼物","lǐwù","quà"],["年级","niánjí","lớp (khối)"],["班","bān","lớp"],["过去","guòqù","quá khứ, trước đây"],["刻","kè","khắc (15 phút)"]],
  sents:[{t:["我","跟","她","认识","五","年","了"],z:"我跟她认识五年了。",p:"Wǒ gēn tā rènshi wǔ nián le.",v:"Mình quen cô ấy 5 năm rồi."},{t:["我们","很","久","没有","见面","了"],z:"我们很久没有见面了。",p:"Wǒmen hěn jiǔ méiyǒu jiànmiàn le.",v:"Lâu lắm rồi chúng mình chưa gặp nhau."},{t:["我","哥哥","去年","结婚","了"],z:"我哥哥去年结婚了。",p:"Wǒ gēge qùnián jiéhūn le.",v:"Anh trai mình cưới năm ngoái."},{t:["这","是","我","送","给","爷爷","的","礼物"],z:"这是我送给爷爷的礼物。",p:"Zhè shì wǒ sòng gěi yéye de lǐwù.",v:"Đây là quà mình tặng ông."}],
  write:["久","礼"]},
 {zh:"你去哪儿我就去哪儿", vi:"Bạn đi đâu tôi đi đó", words:[
   ["城市","chéngshì","thành phố"],["地方","dìfang","nơi, chỗ"],["附近","fùjìn","gần đây, lân cận"],["街道","jiēdào","đường phố"],["超市","chāoshì","siêu thị"],["银行","yínháng","ngân hàng"],["公园","gōngyuán","công viên"],["图书馆","túshūguǎn","thư viện"],["地铁","dìtiě","tàu điện ngầm"],["自行车","zìxíngchē","xe đạp"],["骑","qí","cưỡi, đi (xe đạp, ngựa)"],["船","chuán","thuyền, tàu"],["辆","liàng","chiếc (xe)"],["方便","fāngbiàn","tiện lợi"],["经过","jīngguò","đi qua; trải qua"]],
  sents:[{t:["你","去","哪儿","我","就","去","哪儿"],z:"你去哪儿，我就去哪儿。",p:"Nǐ qù nǎr, wǒ jiù qù nǎr.",v:"Bạn đi đâu, mình đi đó."},{t:["附近","有","超市","吗"],z:"附近有超市吗？",p:"Fùjìn yǒu chāoshì ma?",v:"Gần đây có siêu thị không?"},{t:["坐","地铁","去","图书馆","很","方便"],z:"坐地铁去图书馆很方便。",p:"Zuò dìtiě qù túshūguǎn hěn fāngbiàn.",v:"Đi tàu điện ngầm tới thư viện rất tiện."},{t:["我","骑","自行车","经过","公园"],z:"我骑自行车经过公园。",p:"Wǒ qí zìxíngchē jīngguò gōngyuán.",v:"Mình đạp xe đi qua công viên."}],
  write:["城","骑"]},
 {zh:"她的汉语说得跟中国人一样好", vi:"Cô ấy nói tiếng Trung giỏi như người Trung Quốc", words:[
   ["一样","yíyàng","giống nhau"],["水平","shuǐpíng","trình độ"],["提高","tígāo","nâng cao"],["努力","nǔlì","cố gắng"],["练习","liànxí","luyện tập"],["句子","jùzi","câu"],["词典","cídiǎn","từ điển"],["中文","Zhōngwén","tiếng Trung"],["讲","jiǎng","kể, giảng"],["教","jiāo","dạy"],["聪明","cōngming","thông minh"],["认真","rènzhēn","chăm chỉ, nghiêm túc"],["明白","míngbai","hiểu, rõ ràng"],["清楚","qīngchu","rõ ràng"],["声音","shēngyīn","âm thanh, giọng"]],
  sents:[{t:["她","的","汉语","说","得","跟","中国","人","一样","好"],z:"她的汉语说得跟中国人一样好。",p:"Tā de Hànyǔ shuō de gēn Zhōngguó rén yíyàng hǎo.",v:"Cô ấy nói tiếng Trung giỏi như người Trung Quốc."},{t:["他","学习","很","努力","也","很","认真"],z:"他学习很努力，也很认真。",p:"Tā xuéxí hěn nǔlì, yě hěn rènzhēn.",v:"Bạn ấy học rất cố gắng và chăm chỉ."},{t:["老师","讲","得","很","清楚"],z:"老师讲得很清楚。",p:"Lǎoshī jiǎng de hěn qīngchu.",v:"Thầy giảng rất rõ."},{t:["我","想","提高","我","的","中文","水平"],z:"我想提高我的中文水平。",p:"Wǒ xiǎng tígāo wǒ de Zhōngwén shuǐpíng.",v:"Mình muốn nâng cao trình độ tiếng Trung."}],
  write:["练","教"]},
 {zh:"数学比历史难多了", vi:"Toán khó hơn sử nhiều", words:[
   ["数学","shùxué","môn toán"],["历史","lìshǐ","lịch sử"],["难","nán","khó"],["比较","bǐjiào","khá, tương đối; so sánh"],["成绩","chéngjì","thành tích, điểm số"],["简单","jiǎndān","đơn giản"],["黑板","hēibǎn","bảng đen"],["校长","xiàozhǎng","hiệu trưởng"],["笔记本","bǐjìběn","sổ ghi chép; máy tính xách tay"],["必须","bìxū","phải, bắt buộc"],["回答","huídá","trả lời"],["除了","chúle","ngoài … ra"],["文化","wénhuà","văn hoá"],["世界","shìjiè","thế giới"],["有名","yǒumíng","nổi tiếng"],["更","gèng","càng, hơn"]],
  sents:[{t:["数学","比","历史","难","多","了"],z:"数学比历史难多了。",p:"Shùxué bǐ lìshǐ nán duō le.",v:"Toán khó hơn sử nhiều."},{t:["这","次","考试","我","的","成绩","比较","好"],z:"这次考试我的成绩比较好。",p:"Zhè cì kǎoshì wǒ de chéngjì bǐjiào hǎo.",v:"Lần thi này điểm của mình khá tốt."},{t:["除了","数学","我","还","喜欢","历史"],z:"除了数学，我还喜欢历史。",p:"Chúle shùxué, wǒ hái xǐhuan lìshǐ.",v:"Ngoài toán ra, mình còn thích sử."},{t:["你","必须","回答","这","个","问题"],z:"你必须回答这个问题。",p:"Nǐ bìxū huídá zhè ge wèntí.",v:"Bạn phải trả lời câu hỏi này."}],
  write:["数","历"]},
 {zh:"别忘了把空调关了", vi:"Đừng quên tắt điều hoà", words:[
   ["把","bǎ","(đưa tân ngữ lên trước động từ)"],["空调","kōngtiáo","điều hoà"],["关","guān","đóng, tắt"],["灯","dēng","đèn"],["电梯","diàntī","thang máy"],["楼","lóu","toà nhà, tầng"],["层","céng","tầng"],["打扫","dǎsǎo","quét dọn"],["干净","gānjìng","sạch sẽ"],["洗澡","xǐzǎo","tắm"],["刷牙","shuāyá","đánh răng"],["洗手间","xǐshǒujiān","nhà vệ sinh"],["小心","xiǎoxīn","cẩn thận"],["注意","zhùyì","chú ý"],["坏","huài","hỏng, xấu"]],
  sents:[{t:["别","忘记","把","空调","关","了"],z:"别忘记把空调关了。",p:"Bié wàngjì bǎ kōngtiáo guān le.",v:"Đừng quên tắt điều hoà nhé."},{t:["电梯","坏","了","我","住","在","八","层"],z:"电梯坏了，我住在八层！",p:"Diàntī huài le, wǒ zhù zài bā céng!",v:"Thang máy hỏng rồi, mà mình ở tầng 8!"},{t:["我","把","房间","打扫","干净","了"],z:"我把房间打扫干净了。",p:"Wǒ bǎ fángjiān dǎsǎo gānjìng le.",v:"Mình dọn phòng sạch rồi."},{t:["下雨","了","路","上","要","小心"],z:"下雨了，路上要小心。",p:"Xià yǔ le, lù shang yào xiǎoxīn.",v:"Trời mưa, đi đường cẩn thận nhé."}],
  write:["把","关"]},
 {zh:"把重要的东西放在我这儿吧", vi:"Để đồ quan trọng ở chỗ tôi nhé", words:[
   ["重要","zhòngyào","quan trọng"],["护照","hùzhào","hộ chiếu"],["行李箱","xínglixiāng","va li"],["放心","fàngxīn","yên tâm"],["担心","dānxīn","lo lắng"],["拿","ná","cầm, lấy"],["借","jiè","mượn, cho mượn"],["需要","xūyào","cần"],["留学","liúxué","du học"],["国家","guójiā","đất nước"],["一定","yídìng","nhất định"],["照顾","zhàogù","chăm sóc"],["愿意","yuànyì","bằng lòng, muốn"],["极","jí","cực kỳ"],["当然","dāngrán","tất nhiên"]],
  sents:[{t:["你","把","护照","放","在","包","里","吧"],z:"你把护照放在包里吧。",p:"Nǐ bǎ hùzhào fàng zài bāo li ba.",v:"Bạn để hộ chiếu vào túi nhé."},{t:["放心","我","一定","照顾","好","你","的","猫"],z:"放心，我一定照顾好你的猫。",p:"Fàngxīn, wǒ yídìng zhàogù hǎo nǐ de māo.",v:"Yên tâm, mình nhất định chăm mèo của bạn thật tốt."},{t:["我","可以","借","你","的","行李箱","吗"],z:"我可以借你的行李箱吗？",p:"Wǒ kěyǐ jiè nǐ de xínglixiāng ma?",v:"Mình mượn va li của bạn được không?"},{t:["她","要","去","中国","留学","妈妈","很","担心"],z:"她要去中国留学，妈妈很担心。",p:"Tā yào qù Zhōngguó liúxué, māma hěn dānxīn.",v:"Cô ấy sắp đi du học Trung Quốc, mẹ rất lo."}],
  write:["借","重"]},
 {zh:"我是走回来的", vi:"Tôi đi bộ về", words:[
   ["站","zhàn","đứng; bến, trạm"],["向","xiàng","về phía, hướng"],["东","dōng","phía đông"],["西","xī","phía tây"],["中间","zhōngjiān","ở giữa"],["终于","zhōngyú","cuối cùng (cũng)"],["米","mǐ","mét"],["经常","jīngcháng","thường xuyên"],["或者","huòzhě","hoặc"],["然后","ránhòu","sau đó"],["先","xiān","trước"],["后来","hòulái","sau đó, về sau"],["最后","zuìhòu","cuối cùng"],["故事","gùshi","câu chuyện"],["遇到","yùdào","gặp phải"]],
  sents:[{t:["我","是","走","回","来","的"],z:"我是走回来的。",p:"Wǒ shì zǒu huílai de.",v:"Mình đi bộ về đấy."},{t:["你","先","向","东","走","一","百","米"],z:"你先向东走一百米。",p:"Nǐ xiān xiàng dōng zǒu yìbǎi mǐ.",v:"Bạn đi về phía đông 100 mét trước đã."},{t:["我","在","路","上","遇到","了","一","个","老","朋友"],z:"我在路上遇到了一个老朋友。",p:"Wǒ zài lù shang yùdào le yí ge lǎo péngyou.",v:"Trên đường mình gặp một người bạn cũ."},{t:["我们","等","了","很","久","他","终于","来","了"],z:"我们等了很久，他终于来了。",p:"Wǒmen děng le hěn jiǔ, tā zhōngyú lái le.",v:"Chờ mãi, cuối cùng anh ấy cũng đến."}],
  write:["向","东"]},
 {zh:"你把水果拿过来", vi:"Bạn mang hoa quả lại đây", words:[
   ["新鲜","xīnxiān","tươi"],["元","yuán","đồng (tệ)"],["角","jiǎo","hào (1/10 tệ)"],["分","fēn","phút; điểm; xu"],["万","wàn","vạn, mười nghìn"],["一共","yígòng","tổng cộng"],["花","huā","tiêu (tiền, thời gian)"],["选择","xuǎnzé","lựa chọn"],["张","zhāng","tờ, tấm (lượng từ)"],["位","wèi","vị (lượng từ lịch sự cho người)"],["段","duàn","đoạn, khoảng"],["种","zhǒng","loại, kiểu"],["口","kǒu","miệng; ngụm, (lượng từ)"],["满意","mǎnyì","hài lòng"],["蓝","lán","màu xanh lam"]],
  sents:[{t:["你","把","水果","拿","过","来"],z:"你把水果拿过来。",p:"Nǐ bǎ shuǐguǒ ná guòlai.",v:"Bạn mang hoa quả lại đây."},{t:["这","些","苹果","很","新鲜"],z:"这些苹果很新鲜。",p:"Zhèxiē píngguǒ hěn xīnxiān.",v:"Mấy quả táo này rất tươi."},{t:["这","个","西瓜","八","元","五","角"],z:"这个西瓜八元五角。",p:"Zhè ge xīguā bā yuán wǔ jiǎo.",v:"Quả dưa hấu này 8 tệ 5 hào."},{t:["我","花","了","两","百","元","买","衣服"],z:"我花了两百元买衣服。",p:"Wǒ huā le liǎngbǎi yuán mǎi yīfu.",v:"Mình tiêu 200 tệ mua quần áo."}],
  write:["元","选"]},
 {zh:"其他都没什么问题", vi:"Những cái khác đều không có vấn đề gì", words:[
   ["其他","qítā","khác"],["其实","qíshí","thật ra"],["奇怪","qíguài","kỳ lạ"],["发现","fāxiàn","phát hiện"],["解决","jiějué","giải quyết"],["关于","guānyú","về (vấn đề gì)"],["根据","gēnjù","căn cứ vào"],["要求","yāoqiú","yêu cầu"],["完成","wánchéng","hoàn thành"],["结束","jiéshù","kết thúc"],["节目","jiémù","chương trình"],["新闻","xīnwén","tin tức"],["上网","shàngwǎng","lên mạng"],["音乐","yīnyuè","âm nhạc"],["如果","rúguǒ","nếu"]],
  sents:[{t:["其他","都","没有","什么","问题"],z:"其他都没有什么问题。",p:"Qítā dōu méiyǒu shénme wèntí.",v:"Những cái khác đều không có vấn đề gì."},{t:["这","个","问题","我","已经","解决","了"],z:"这个问题我已经解决了。",p:"Zhè ge wèntí wǒ yǐjīng jiějué le.",v:"Vấn đề này mình giải quyết xong rồi."},{t:["我","发现","他","今天","很","奇怪"],z:"我发现他今天很奇怪。",p:"Wǒ fāxiàn tā jīntiān hěn qíguài.",v:"Mình thấy hôm nay anh ấy rất lạ."},{t:["如果","你","完成","了","作业","就","可以","上网"],z:"如果你完成了作业，就可以上网。",p:"Rúguǒ nǐ wánchéng le zuòyè, jiù kěyǐ shàngwǎng.",v:"Nếu con làm xong bài tập thì được lên mạng."}],
  write:["其","解"]},
 {zh:"我现在累得下了班就想睡觉", vi:"Giờ tôi mệt đến mức tan làm là muốn ngủ", words:[
   ["习惯","xíguàn","thói quen; quen"],["一般","yìbān","thông thường"],["几乎","jīhū","hầu như"],["特别","tèbié","đặc biệt"],["只","zhǐ","chỉ"],["又","yòu","lại"],["还是","háishi","hay là; vẫn"],["多么","duōme","biết bao, thật là"],["地","de","(trợ từ, đứng trước động từ)"],["关心","guānxīn","quan tâm"],["生气","shēngqì","tức giận"],["哭","kū","khóc"],["难过","nánguò","buồn"],["害怕","hàipà","sợ"],["安静","ānjìng","yên tĩnh"]],
  sents:[{t:["我","现在","累","得","下","了","班","就","想","睡觉"],z:"我现在累得下了班就想睡觉。",p:"Wǒ xiànzài lèi de xià le bān jiù xiǎng shuìjiào.",v:"Giờ mình mệt đến mức tan làm là chỉ muốn ngủ."},{t:["我","习惯","早上","六","点","起床"],z:"我习惯早上六点起床。",p:"Wǒ xíguàn zǎoshang liù diǎn qǐchuáng.",v:"Mình quen dậy lúc 6 giờ sáng."},{t:["他","又","迟到","了","老师","很","生气"],z:"他又迟到了，老师很生气。",p:"Tā yòu chídào le, lǎoshī hěn shēngqì.",v:"Bạn ấy lại đến muộn, cô giáo rất giận."},{t:["她","一般","只","喝","茶","不","喝","咖啡"],z:"她一般只喝茶，不喝咖啡。",p:"Tā yìbān zhǐ hē chá, bù hē kāfēi.",v:"Cô ấy thường chỉ uống trà, không uống cà phê."}],
  write:["习","惯"]},
 {zh:"谁都有办法看好你的“病”", vi:"Ai cũng có cách chữa “bệnh” của bạn", words:[
   ["办法","bànfǎ","cách, biện pháp"],["发烧","fāshāo","sốt"],["感冒","gǎnmào","cảm cúm"],["检查","jiǎnchá","kiểm tra, khám"],["舒服","shūfu","dễ chịu, khoẻ"],["变化","biànhuà","thay đổi"],["环境","huánjìng","môi trường"],["动物","dòngwù","động vật"],["熊猫","xióngmāo","gấu trúc"],["鸟","niǎo","chim"],["马","mǎ","con ngựa"],["草","cǎo","cỏ"],["树","shù","cây"],["花","huā","hoa"],["长","zhǎng","lớn lên, mọc"]],
  sents:[{t:["别","担心","我","有","办法"],z:"别担心，我有办法。",p:"Bié dānxīn, wǒ yǒu bànfǎ.",v:"Đừng lo, mình có cách."},{t:["你","发烧","了","快","去","医院","检查","一下"],z:"你发烧了，快去医院检查一下。",p:"Nǐ fāshāo le, kuài qù yīyuàn jiǎnchá yíxià.",v:"Bạn sốt rồi, mau đi viện khám đi."},{t:["公园","里","的","树","长","得","很","高"],z:"公园里的树长得很高。",p:"Gōngyuán li de shù zhǎng de hěn gāo.",v:"Cây trong công viên mọc rất cao."},{t:["熊猫","是","很","可爱","的","动物"],z:"熊猫是很可爱的动物。",p:"Xióngmāo shì hěn kě'ài de dòngwù.",v:"Gấu trúc là loài vật rất dễ thương."}],
  write:["办","树"]},
 {zh:"我相信他们会同意的", vi:"Tôi tin họ sẽ đồng ý", words:[
   ["相信","xiāngxìn","tin tưởng"],["同意","tóngyì","đồng ý"],["决定","juédìng","quyết định"],["认为","rènwéi","cho rằng"],["应该","yīnggāi","nên"],["只有……才……","zhǐyǒu……cái……","chỉ có … mới …"],["不但……而且……","búdàn……érqiě……","không những … mà còn …"],["为","wèi","vì, cho"],["为了","wèile","để, vì"],["主要","zhǔyào","chủ yếu"],["别人","biérén","người khác"],["容易","róngyì","dễ"],["老","lǎo","già, cũ"],["差","chà","kém, thiếu"],["短","duǎn","ngắn"]],
  sents:[{t:["我","相信","爸爸","妈妈","会","同意","的"],z:"我相信爸爸妈妈会同意的。",p:"Wǒ xiāngxìn bàba māma huì tóngyì de.",v:"Mình tin bố mẹ sẽ đồng ý."},{t:["我","认为","你","应该","自己","决定"],z:"我认为你应该自己决定。",p:"Wǒ rènwéi nǐ yīnggāi zìjǐ juédìng.",v:"Mình nghĩ bạn nên tự quyết định."},{t:["只有","努力","学习","才","能","提高","成绩"],z:"只有努力学习，才能提高成绩。",p:"Zhǐyǒu nǔlì xuéxí, cái néng tígāo chéngjì.",v:"Chỉ có chăm học mới nâng được điểm."},{t:["他","不但","聪明","而且","很","努力"],z:"他不但聪明，而且很努力。",p:"Tā búdàn cōngming, érqiě hěn nǔlì.",v:"Bạn ấy không những thông minh mà còn rất chăm."}],
  write:["信","同"]},
 {zh:"你没看出来吗？", vi:"Bạn không nhận ra à?", words:[
   ["起来","qǐlai","đứng dậy; (bổ ngữ xu hướng)"],["刮风","guā fēng","nổi gió"],["季节","jìjié","mùa"],["春","chūn","mùa xuân"],["夏","xià","mùa hè"],["秋","qiū","mùa thu"],["冬","dōng","mùa đông"],["太阳","tàiyáng","mặt trời"],["月亮","yuèliang","mặt trăng"],["黄河","Huáng Hé","sông Hoàng Hà"],["绿","lǜ","màu xanh lá"],["半","bàn","một nửa, rưỡi"],["渴","kě","khát"],["过","guò","qua, trải qua"]],
  sents:[{t:["你","没有","看","出","来","吗"],z:"你没有看出来吗？",p:"Nǐ méiyǒu kàn chūlai ma?",v:"Bạn không nhận ra à?"},{t:["你","最","喜欢","哪","个","季节"],z:"你最喜欢哪个季节？",p:"Nǐ zuì xǐhuan nǎ ge jìjié?",v:"Bạn thích mùa nào nhất?"},{t:["春","夏","秋","冬","我","都","喜欢"],z:"春夏秋冬我都喜欢。",p:"Chūn xià qiū dōng wǒ dōu xǐhuan.",v:"Xuân, hạ, thu, đông mình đều thích."},{t:["今天","刮风","了","天气","很","冷"],z:"今天刮风了，天气很冷。",p:"Jīntiān guā fēng le, tiānqì hěn lěng.",v:"Hôm nay nổi gió, trời rất lạnh."}],
  write:["春","秋"]},
 {zh:"我被他影响了", vi:"Tôi bị anh ấy ảnh hưởng", words:[
   ["被","bèi","bị, được (câu bị động)"],["影响","yǐngxiǎng","ảnh hưởng"],["爱好","àihào","sở thích"],["感兴趣","gǎn xìngqù","có hứng thú"],["画","huà","vẽ; bức tranh"],["比赛","bǐsài","cuộc thi, trận đấu"],["参加","cānjiā","tham gia"],["机会","jīhuì","cơ hội"],["一边","yìbiān","vừa … vừa …"],["以前","yǐqián","trước đây"],["试","shì","thử"],["用","yòng","dùng"],["发","fā","gửi, phát"],["啊","a","à, nhé (trợ từ cảm thán)"],["帮忙","bāngmáng","giúp đỡ"]],
  sents:[{t:["我","被","他","影响","了"],z:"我被他影响了。",p:"Wǒ bèi tā yǐngxiǎng le.",v:"Mình bị anh ấy ảnh hưởng."},{t:["你","有","什么","爱好"],z:"你有什么爱好？",p:"Nǐ yǒu shénme àihào?",v:"Bạn có sở thích gì?"},{t:["我","对","画","画","很","感兴趣"],z:"我对画画很感兴趣。",p:"Wǒ duì huà huà hěn gǎn xìngqù.",v:"Mình rất thích vẽ tranh."},{t:["他","参加","了","学校","的","游泳","比赛"],z:"他参加了学校的游泳比赛。",p:"Tā cānjiā le xuéxiào de yóuyǒng bǐsài.",v:"Bạn ấy tham gia cuộc thi bơi của trường."}],
  write:["被","影"]},
 {zh:"复习", vi:"Ôn tập cả sách", review:true, words:[], sents:[], write:[]}
];
const EXTRA_PY = { "不但": "búdàn", "而且": "érqiě", "只有": "zhǐyǒu", "才": "cái" };
