/* ================== GIÁO TRÌNH HSK 4 — 600 từ chính thức (HSK 2.0), chia theo 20 bài của sách HSK标准教程 4上 + 4下 ================== */
const LESSONS = [
 {zh:"简单的爱情", vi:"Tình yêu giản dị", words:[
   ["爱情","àiqíng","tình yêu"],["不仅","bùjǐn","không chỉ"],["从来","cónglái","xưa nay, từ trước tới giờ"],["法律","fǎlǜ","pháp luật"],["感动","gǎndòng","cảm động"],["刚","gāng","vừa mới"],
   ["共同","gòngtóng","chung, cùng nhau"],["够","gòu","đủ"],["互相","hùxiāng","lẫn nhau"],["即使","jíshǐ","cho dù"],["加班","jiā bān","tăng ca"],["接受","jiēshòu","chấp nhận, tiếp nhận"],
   ["开玩笑","kāi wánxiào","nói đùa"],["浪漫","làngmàn","lãng mạn"],["俩","liǎ","hai (người)"],["脾气","píqi","tính khí"],["缺点","quēdiǎn","khuyết điểm"],["深","shēn","sâu"],
   ["生活","shēnghuó","cuộc sống; sống"],["适合","shìhé","phù hợp"],["熟悉","shúxī","quen thuộc"],["吸引","xīyǐn","thu hút"],["羡慕","xiànmù","ngưỡng mộ"],["幸福","xìngfú","hạnh phúc"],
   ["性格","xìnggé","tính cách"],["印象","yìnxiàng","ấn tượng"],["优点","yōudiǎn","ưu điểm"],["幽默","yōumò","hài hước"],["原因","yuányīn","nguyên nhân"],["自然","zìrán","tự nhiên"],
   ["最好","zuìhǎo","tốt nhất là"]],
  sents:[{t:["他","俩","的","性格","很","适合"],z:"他俩的性格很适合。",p:"Tā liǎ de xìnggé hěn shìhé.",v:"Tính cách hai người họ rất hợp nhau."},{t:["我","很","羡慕","你","的","幸福","生活"],z:"我很羡慕你的幸福生活。",p:"Wǒ hěn xiànmù nǐ de xìngfú shēnghuó.",v:"Tôi rất ngưỡng mộ cuộc sống hạnh phúc của bạn."},{t:["他","很","幽默","这","是","他","最","大","的","优点"],z:"他很幽默，这是他最大的优点。",p:"Tā hěn yōumò, zhè shì tā zuì dà de yōudiǎn.",v:"Anh ấy hài hước, đó là ưu điểm lớn nhất."},{t:["我","对","他","的","印象","很","深"],z:"我对他的印象很深。",p:"Wǒ duì tā de yìnxiàng hěn shēn.",v:"Tôi có ấn tượng rất sâu về anh ấy."}],
  write:["情","福"]},
 {zh:"真正的朋友", vi:"Người bạn thật sự", words:[
   ["抱歉","bàoqiàn","xin lỗi, áy náy"],["诚实","chéngshí","thật thà"],["打扰","dǎrǎo","làm phiền"],["当时","dāngshí","lúc đó"],["道歉","dào qiàn","xin lỗi"],["感情","gǎnqíng","tình cảm"],
   ["感谢","gǎnxiè","cảm ơn, biết ơn"],["故意","gùyì","cố ý"],["害羞","hàixiū","xấu hổ, ngại"],["回忆","huíyì","kỷ niệm; nhớ lại"],["交流","jiāoliú","trao đổi, giao lưu"],["拒绝","jùjué","từ chối"],
   ["距离","jùlí","khoảng cách"],["聚会","jùhuì","buổi họp mặt"],["可怜","kělián","đáng thương"],["理解","lǐjiě","hiểu, thông cảm"],["联系","liánxì","liên lạc"],["骗","piàn","lừa"],
   ["商量","shāngliang","bàn bạc"],["谈","tán","nói chuyện, bàn"],["讨厌","tǎoyàn","ghét"],["同情","tóngqíng","đồng cảm, thương"],["误会","wùhuì","hiểu lầm"],["友好","yǒuhǎo","thân thiện"],
   ["友谊","yǒuyì","tình bạn"],["原谅","yuánliàng","tha thứ"],["真正","zhēnzhèng","thật sự"],["支持","zhīchí","ủng hộ"],["主意","zhǔyi","ý kiến, ý tưởng"],["尊重","zūnzhòng","tôn trọng"]],
  sents:[{t:["真正","的","朋友","会","互相","支持"],z:"真正的朋友会互相支持。",p:"Zhēnzhèng de péngyou huì hùxiāng zhīchí.",v:"Bạn thật sự sẽ ủng hộ lẫn nhau."},{t:["对不起","我","不","是","故意","的"],z:"对不起，我不是故意的。",p:"Duìbuqǐ, wǒ bú shì gùyì de.",v:"Xin lỗi, mình không cố ý."},{t:["这","是","一","个","误会","请","你","原谅","我"],z:"这是一个误会，请你原谅我。",p:"Zhè shì yí ge wùhuì, qǐng nǐ yuánliàng wǒ.",v:"Đây là hiểu lầm, mong bạn tha thứ cho mình."},{t:["我们","经常","用","手机","联系"],z:"我们经常用手机联系。",p:"Wǒmen jīngcháng yòng shǒujī liánxì.",v:"Chúng mình hay liên lạc qua điện thoại."}],
  write:["友","真"]},
 {zh:"经理对我印象不错", vi:"Giám đốc có ấn tượng tốt về tôi", words:[
   ["安排","ānpái","sắp xếp"],["按照","ànzhào","theo, dựa theo"],["毕业","bì yè","tốt nghiệp"],["表格","biǎogé","bảng, mẫu đơn"],["博士","bóshì","tiến sĩ"],["材料","cáiliào","tài liệu, vật liệu"],
   ["出差","chū chāi","đi công tác"],["份","fèn","phần; bản (lượng từ)"],["符合","fúhé","phù hợp, đáp ứng"],["负责","fùzé","phụ trách; có trách nhiệm"],["管理","guǎnlǐ","quản lý"],["奖金","jiǎngjīn","tiền thưởng"],
   ["紧张","jǐnzhāng","căng thẳng, hồi hộp"],["经验","jīngyàn","kinh nghiệm"],["能力","nénglì","năng lực"],["任务","rènwu","nhiệm vụ"],["申请","shēnqǐng","xin, nộp đơn"],["适应","shìyìng","thích ứng"],
   ["顺利","shùnlì","thuận lợi"],["硕士","shuòshì","thạc sĩ"],["态度","tàidu","thái độ"],["提前","tíqián","trước, sớm hơn"],["通知","tōngzhī","thông báo"],["应聘","yìngpìn","ứng tuyển"],
   ["优秀","yōuxiù","xuất sắc"],["责任","zérèn","trách nhiệm"],["招聘","zhāopìn","tuyển dụng"],["正式","zhèngshì","chính thức"],["职业","zhíyè","nghề nghiệp"],["专业","zhuānyè","chuyên ngành"]],
  sents:[{t:["我","下","个","月","要","去","北京","出差"],z:"我下个月要去北京出差。",p:"Wǒ xià ge yuè yào qù Běijīng chū chāi.",v:"Tháng sau tôi phải đi Bắc Kinh công tác."},{t:["我","去年","毕业","专业","是","汉语"],z:"我去年毕业，专业是汉语。",p:"Wǒ qùnián bì yè, zhuānyè shì Hànyǔ.",v:"Tôi tốt nghiệp năm ngoái, chuyên ngành tiếng Trung."},{t:["这","家","公司","在","招聘","经理"],z:"这家公司在招聘经理。",p:"Zhè jiā gōngsī zài zhāopìn jīnglǐ.",v:"Công ty này đang tuyển giám đốc."},{t:["他","工作","很","负责","态度","也","很","好"],z:"他工作很负责，态度也很好。",p:"Tā gōngzuò hěn fùzé, tàidu yě hěn hǎo.",v:"Anh ấy làm việc có trách nhiệm, thái độ cũng tốt."}],
  write:["职","专"]},
 {zh:"不要太着急赚钱", vi:"Đừng quá vội kiếm tiền", words:[
   ["不得不","bùdébù","buộc phải"],["超过","chāoguò","vượt quá"],["成为","chéngwéi","trở thành"],["存","cún","gửi (tiền), cất giữ"],["当","dāng","làm, đảm nhiệm"],["得","děi","phải, cần"],
   ["干","gàn","làm (việc)"],["工资","gōngzī","tiền lương"],["关键","guānjiàn","then chốt"],["获得","huòdé","giành được, đạt được"],["积累","jīlěi","tích luỹ"],["计划","jìhuà","kế hoạch"],
   ["将来","jiānglái","tương lai"],["交","jiāo","nộp, giao; kết (bạn)"],["经济","jīngjì","kinh tế"],["竞争","jìngzhēng","cạnh tranh"],["考虑","kǎolǜ","cân nhắc, suy nghĩ"],["理想","lǐxiǎng","lý tưởng, ước mơ"],
   ["目的","mùdì","mục đích"],["取","qǔ","lấy, rút (tiền)"],["生意","shēngyi","việc buôn bán"],["省","shěng","tiết kiệm; tỉnh"],["实际","shíjì","thực tế"],["通过","tōngguò","thông qua; vượt qua"],
   ["辛苦","xīnkǔ","vất vả"],["压力","yālì","áp lực"],["暂时","zànshí","tạm thời"],["值得","zhíde","đáng"],["赚","zhuàn","kiếm (tiền)"]],
  sents:[{t:["不","要","太","着急","赚","钱"],z:"不要太着急赚钱。",p:"Bú yào tài zháojí zhuàn qián.",v:"Đừng quá vội kiếm tiền."},{t:["年轻","人","应该","多","积累","经验"],z:"年轻人应该多积累经验。",p:"Niánqīng rén yīnggāi duō jīlěi jīngyàn.",v:"Người trẻ nên tích luỹ nhiều kinh nghiệm."},{t:["我","的","理想","是","当","医生"],z:"我的理想是当医生。",p:"Wǒ de lǐxiǎng shì dāng yīshēng.",v:"Ước mơ của tôi là làm bác sĩ."},{t:["我","每","个","月","都","存","一点儿","钱"],z:"我每个月都存一点儿钱。",p:"Wǒ měi ge yuè dōu cún yìdiǎnr qián.",v:"Mỗi tháng tôi đều để dành một ít tiền."}],
  write:["赚","存"]},
 {zh:"只买对的，不买贵的", vi:"Chỉ mua đúng, không mua đắt", words:[
   ["饼干","bǐnggān","bánh quy"],["打折","dǎ zhé","giảm giá"],["底","dǐ","đáy; cuối (tháng, năm)"],["否则","fǒuzé","nếu không thì"],["付款","fù kuǎn","thanh toán"],["购物","gòuwù","mua sắm"],
   ["顾客","gùkè","khách hàng"],["广告","guǎnggào","quảng cáo"],["逛","guàng","đi dạo, đi (phố)"],["合适","héshì","vừa, hợp"],["盒子","hézi","cái hộp"],["价格","jiàgé","giá cả"],
   ["矿泉水","kuàngquánshuǐ","nước khoáng"],["零钱","língqián","tiền lẻ"],["流行","liúxíng","thịnh hành, mốt"],["满","mǎn","đầy"],["毛","máo","hào (1/10 tệ); lông"],["毛巾","máojīn","khăn mặt"],
   ["免费","miǎnfèi","miễn phí"],["排队","pái duì","xếp hàng"],["巧克力","qiǎokèlì","sô-cô-la"],["收","shōu","nhận, thu"],["售货员","shòuhuòyuán","nhân viên bán hàng"],["提","tí","xách; nhắc đến"],
   ["袜子","wàzi","tất, vớ"],["现金","xiànjīn","tiền mặt"],["牙膏","yágāo","kem đánh răng"]],
  sents:[{t:["这","件","衣服","在","打折"],z:"这件衣服在打折。",p:"Zhè jiàn yīfu zài dǎ zhé.",v:"Chiếc áo này đang giảm giá."},{t:["我","周末","喜欢","去","商店","逛","逛"],z:"我周末喜欢去商店逛逛。",p:"Wǒ zhōumò xǐhuan qù shāngdiàn guàngguang.",v:"Cuối tuần tôi thích đi dạo cửa hàng."},{t:["超市","里","的","顾客","都","在","排队","付款"],z:"超市里的顾客都在排队付款。",p:"Chāoshì li de gùkè dōu zài pái duì fù kuǎn.",v:"Khách trong siêu thị đều đang xếp hàng trả tiền."},{t:["这","双","袜子","的","价格","很","合适"],z:"这双袜子的价格很合适。",p:"Zhè shuāng wàzi de jiàgé hěn héshì.",v:"Giá đôi tất này rất hợp lý."}],
  write:["购","价"]},
 {zh:"一分钱一分货", vi:"Tiền nào của nấy", words:[
   ["百分之","bǎi fēn zhī","phần trăm"],["保证","bǎozhèng","bảo đảm"],["倍","bèi","lần (gấp)"],["差不多","chàbuduō","gần như, xấp xỉ"],["大约","dàyuē","khoảng"],["低","dī","thấp"],
   ["合格","hégé","đạt chuẩn"],["厚","hòu","dày"],["假","jiǎ","giả"],["降低","jiàngdī","hạ thấp, giảm"],["另外","lìngwài","ngoài ra"],["麻烦","máfan","phiền phức; làm phiền"],
   ["破","pò","rách, vỡ"],["普遍","pǔbiàn","phổ biến"],["轻","qīng","nhẹ"],["区别","qūbié","sự khác biệt"],["全部","quánbù","toàn bộ"],["数量","shùliàng","số lượng"],
   ["特点","tèdiǎn","đặc điểm"],["相同","xiāngtóng","giống nhau"],["效果","xiàoguǒ","hiệu quả"],["修理","xiūlǐ","sửa chữa"],["眼镜","yǎnjìng","kính mắt"],["样子","yàngzi","kiểu dáng, dáng vẻ"],
   ["之","zhī","của (văn viết)"],["质量","zhìliàng","chất lượng"],["重","zhòng","nặng"],["左右","zuǒyòu","khoảng, chừng"]],
  sents:[{t:["这","双","皮鞋","质量","很","好"],z:"这双皮鞋质量很好。",p:"Zhè shuāng píxié zhìliàng hěn hǎo.",v:"Đôi giày da này chất lượng rất tốt."},{t:["我","的","眼镜","破","了","要","去","修理"],z:"我的眼镜破了，要去修理。",p:"Wǒ de yǎnjìng pò le, yào qù xiūlǐ.",v:"Kính của tôi vỡ rồi, phải đi sửa."},{t:["这","两","个","手机","有","什么","区别"],z:"这两个手机有什么区别？",p:"Zhè liǎng ge shǒujī yǒu shénme qūbié?",v:"Hai chiếc điện thoại này khác nhau gì?"},{t:["价格","低","的","东西","不","一定","好"],z:"价格低的东西不一定好。",p:"Jiàgé dī de dōngxi bù yídìng hǎo.",v:"Đồ giá rẻ chưa chắc đã tốt."}],
  write:["质","量"]},
 {zh:"最好的医生是自己", vi:"Bác sĩ tốt nhất là chính mình", words:[
   ["按时","ànshí","đúng giờ"],["抽烟","chōu yān","hút thuốc"],["打针","dǎ zhēn","tiêm"],["大夫","dàifu","bác sĩ"],["肚子","dùzi","bụng"],["放松","fàngsōng","thả lỏng"],
   ["感觉","gǎnjué","cảm thấy; cảm giác"],["胳膊","gēbo","cánh tay"],["汗","hàn","mồ hôi"],["好处","hǎochu","lợi ích"],["护士","hùshi","y tá"],["及时","jíshí","kịp thời"],
   ["减肥","jiǎn féi","giảm cân"],["建议","jiànyì","khuyên; lời khuyên"],["咳嗽","késou","ho"],["恐怕","kǒngpà","e rằng"],["困","kùn","buồn ngủ"],["力气","lìqi","sức lực"],
   ["难受","nánshòu","khó chịu"],["皮肤","pífū","da"],["散步","sàn bù","đi dạo"],["受不了","shòu bu liǎo","không chịu nổi"],["躺","tǎng","nằm"],["提醒","tíxǐng","nhắc nhở"],
   ["醒","xǐng","tỉnh (ngủ)"],["严重","yánzhòng","nghiêm trọng"],["正常","zhèngcháng","bình thường"],["至少","zhìshǎo","ít nhất"]],
  sents:[{t:["我","最近","感觉","很","困"],z:"我最近感觉很困。",p:"Wǒ zuìjìn gǎnjué hěn kùn.",v:"Dạo này tôi thấy rất buồn ngủ."},{t:["大夫","建议","我","别","抽烟"],z:"大夫建议我别抽烟。",p:"Dàifu jiànyì wǒ bié chōu yān.",v:"Bác sĩ khuyên tôi đừng hút thuốc."},{t:["我","肚子","疼","很","难受"],z:"我肚子疼，很难受。",p:"Wǒ dùzi téng, hěn nánshòu.",v:"Tôi đau bụng, rất khó chịu."},{t:["我","每","个","星期","至少","运动","三","次"],z:"我每个星期至少运动三次。",p:"Wǒ měi ge xīngqī zhìshǎo yùndòng sān cì.",v:"Mỗi tuần tôi vận động ít nhất ba lần."}],
  write:["汗","醒"]},
 {zh:"生活中不缺少美", vi:"Cuộc sống không thiếu cái đẹp", words:[
   ["打扮","dǎban","trang điểm, ăn diện"],["戴","dài","đeo, đội"],["动作","dòngzuò","động tác"],["丰富","fēngfù","phong phú"],["活动","huódòng","hoạt động"],["接着","jiēzhe","tiếp theo, tiếp tục"],
   ["镜子","jìngzi","gương"],["理发","lǐ fà","cắt tóc"],["厉害","lìhai","giỏi; ghê gớm"],["美丽","měilì","đẹp"],["偶尔","ǒu'ěr","thỉnh thoảng"],["乒乓球","pīngpāngqiú","bóng bàn"],
   ["平时","píngshí","ngày thường"],["轻松","qīngsōng","nhẹ nhàng, thoải mái"],["缺少","quēshǎo","thiếu"],["输","shū","thua"],["帅","shuài","đẹp trai"],["弹钢琴","tán gāngqín","chơi đàn piano"],
   ["挺","tǐng","khá, rất"],["完全","wánquán","hoàn toàn"],["网球","wǎngqiú","quần vợt"],["无聊","wúliáo","buồn chán"],["笑话","xiàohua","truyện cười; chê cười"],["心情","xīnqíng","tâm trạng"],
   ["呀","ya","à, nhé (trợ từ)"],["阳光","yángguāng","ánh nắng"],["艺术","yìshù","nghệ thuật"],["赢","yíng","thắng"],["有趣","yǒuqù","thú vị"],["羽毛球","yǔmáoqiú","cầu lông"],
   ["原来","yuánlái","hoá ra; vốn là"],["照","zhào","soi, chiếu; chụp"]],
  sents:[{t:["生活","里","不","缺少","美丽","的","东西"],z:"生活里不缺少美丽的东西。",p:"Shēnghuó li bù quēshǎo měilì de dōngxi.",v:"Cuộc sống không thiếu những điều đẹp đẽ."},{t:["她","在","照","镜子"],z:"她在照镜子。",p:"Tā zài zhào jìngzi.",v:"Cô ấy đang soi gương."},{t:["我","平时","喜欢","弹钢琴"],z:"我平时喜欢弹钢琴。",p:"Wǒ píngshí xǐhuan tán gāngqín.",v:"Ngày thường tôi thích chơi piano."},{t:["今天","阳光","很","好","我","的","心情","也","挺","好"],z:"今天阳光很好，我的心情也挺好。",p:"Jīntiān yángguāng hěn hǎo, wǒ de xīnqíng yě tǐng hǎo.",v:"Hôm nay nắng đẹp, tâm trạng tôi cũng khá tốt."}],
  write:["美","丽"]},
 {zh:"阳光总在风雨后", vi:"Sau mưa trời lại sáng", words:[
   ["不管","bùguǎn","bất kể"],["成功","chénggōng","thành công"],["重新","chóngxīn","lại từ đầu"],["得意","déyì","đắc ý"],["烦恼","fánnǎo","buồn phiền"],["放弃","fàngqì","từ bỏ"],
   ["改变","gǎibiàn","thay đổi"],["敢","gǎn","dám"],["过程","guòchéng","quá trình"],["后悔","hòuhuǐ","hối hận"],["积极","jījí","tích cực"],["既然","jìrán","đã… thì"],
   ["继续","jìxù","tiếp tục"],["坚持","jiānchí","kiên trì"],["结果","jiéguǒ","kết quả"],["尽管","jǐnguǎn","mặc dù"],["经历","jīnglì","trải qua; trải nghiệm"],["困难","kùnnan","khó khăn"],
   ["冷静","lěngjìng","bình tĩnh"],["却","què","nhưng lại"],["然而","rán'ér","tuy nhiên"],["仍然","réngrán","vẫn"],["伤心","shāng xīn","đau lòng"],["失败","shībài","thất bại"],
   ["失望","shīwàng","thất vọng"],["实在","shízài","thật sự"],["无论","wúlùn","bất kể"],["信心","xìnxīn","niềm tin"],["要是","yàoshi","nếu"],["勇敢","yǒnggǎn","dũng cảm"]],
  sents:[{t:["不","要","放弃","要","坚持","下","去"],z:"不要放弃，要坚持下去。",p:"Bú yào fàngqì, yào jiānchí xiàqu.",v:"Đừng bỏ cuộc, phải kiên trì tiếp."},{t:["遇到","困难","的","时候","要","冷静"],z:"遇到困难的时候要冷静。",p:"Yùdào kùnnan de shíhou yào lěngjìng.",v:"Khi gặp khó khăn phải bình tĩnh."},{t:["我","对","自己","很","有","信心"],z:"我对自己很有信心。",p:"Wǒ duì zìjǐ hěn yǒu xìnxīn.",v:"Tôi rất tin vào bản thân."},{t:["这","次","失败","了","我们","可以","重新","开始"],z:"这次失败了，我们可以重新开始。",p:"Zhè cì shībài le, wǒmen kěyǐ chóngxīn kāishǐ.",v:"Lần này thất bại, ta có thể làm lại từ đầu."}],
  write:["坚","持"]},
 {zh:"幸福的标准", vi:"Tiêu chuẩn của hạnh phúc", words:[
   ["抱","bào","ôm, bế"],["标准","biāozhǔn","tiêu chuẩn"],["出生","chūshēng","sinh ra"],["方面","fāngmiàn","phương diện, mặt"],["父亲","fùqīn","cha, bố"],["富","fù","giàu"],
   ["开心","kāixīn","vui vẻ"],["礼拜天","lǐbàitiān","chủ nhật"],["律师","lǜshī","luật sư"],["梦","mèng","giấc mơ"],["母亲","mǔqīn","mẹ"],["年龄","niánlíng","tuổi tác"],
   ["陪","péi","đi cùng, ở bên"],["亲戚","qīnqi","họ hàng"],["穷","qióng","nghèo"],["社会","shèhuì","xã hội"],["十分","shífēn","vô cùng, rất"],["收入","shōurù","thu nhập"],
   ["孙子","sūnzi","cháu nội (trai)"],["条件","tiáojiàn","điều kiện"],["往往","wǎngwǎng","thường thường"],["小伙子","xiǎohuǒzi","chàng trai trẻ"],["性别","xìngbié","giới tính"],["一切","yíqiè","tất cả"],
   ["永远","yǒngyuǎn","mãi mãi"],["愉快","yúkuài","vui vẻ"],["约会","yuēhuì","hẹn hò"],["只要","zhǐyào","chỉ cần"],["祝贺","zhùhè","chúc mừng"]],
  sents:[{t:["每","个","人","幸福","的","标准","不","一样"],z:"每个人幸福的标准不一样。",p:"Měi ge rén xìngfú de biāozhǔn bù yíyàng.",v:"Tiêu chuẩn hạnh phúc của mỗi người khác nhau."},{t:["只要","家","人","健康","我","就","很","开心"],z:"只要家人健康，我就很开心。",p:"Zhǐyào jiā rén jiànkāng, wǒ jiù hěn kāixīn.",v:"Chỉ cần người nhà khoẻ là tôi vui rồi."},{t:["礼拜天","我","陪","母亲","去","公园"],z:"礼拜天我陪母亲去公园。",p:"Lǐbàitiān wǒ péi mǔqīn qù gōngyuán.",v:"Chủ nhật tôi đưa mẹ đi công viên."},{t:["祝贺","你","找","到","了","新","工作"],z:"祝贺你找到了新工作！",p:"Zhùhè nǐ zhǎodào le xīn gōngzuò!",v:"Chúc mừng bạn tìm được việc mới!"}],
  write:["标","梦"]},
 {zh:"读书好，读好书，好读书", vi:"Đọc sách tốt, đọc sách hay, ham đọc sách", words:[
   ["报名","bào míng","đăng ký"],["比如","bǐrú","ví dụ như"],["遍","biàn","lượt (từ đầu đến cuối)"],["词语","cíyǔ","từ ngữ"],["等","děng","vân vân"],["对话","duìhuà","đối thoại"],
   ["翻译","fānyì","phiên dịch"],["节","jié","tiết học; ngày lễ"],["例如","lìrú","ví dụ"],["流利","liúlì","lưu loát"],["内容","nèiróng","nội dung"],["排列","páiliè","sắp xếp"],
   ["篇","piān","bài (lượng từ bài viết)"],["普通话","pǔtōnghuà","tiếng phổ thông"],["日记","rìjì","nhật ký"],["顺序","shùnxù","thứ tự"],["讨论","tǎolùn","thảo luận"],["填空","tián kòng","điền vào chỗ trống"],
   ["文章","wénzhāng","bài văn"],["小说","xiǎoshuō","tiểu thuyết"],["页","yè","trang"],["语法","yǔfǎ","ngữ pháp"],["语言","yǔyán","ngôn ngữ"],["阅读","yuèdú","đọc (hiểu)"],
   ["杂志","zázhì","tạp chí"],["知识","zhīshi","kiến thức"],["重点","zhòngdiǎn","trọng điểm"],["总结","zǒngjié","tổng kết"],["作家","zuòjiā","nhà văn"],["作者","zuòzhě","tác giả"]],
  sents:[{t:["我","报名","参加","了","汉语","比赛"],z:"我报名参加了汉语比赛。",p:"Wǒ bào míng cānjiā le Hànyǔ bǐsài.",v:"Tôi đã đăng ký thi tiếng Trung."},{t:["这","篇","文章","我","读","了","三","遍"],z:"这篇文章我读了三遍。",p:"Zhè piān wénzhāng wǒ dú le sān biàn.",v:"Bài văn này tôi đọc ba lượt rồi."},{t:["她","的","普通话","说","得","很","流利"],z:"她的普通话说得很流利。",p:"Tā de pǔtōnghuà shuō de hěn liúlì.",v:"Cô ấy nói tiếng phổ thông rất lưu loát."},{t:["读","小说","可以","学习","很","多","知识"],z:"读小说可以学习很多知识。",p:"Dú xiǎoshuō kěyǐ xuéxí hěn duō zhīshi.",v:"Đọc tiểu thuyết học được nhiều kiến thức."}],
  write:["语","言"]},
 {zh:"用心发现世界", vi:"Dùng trái tim khám phá thế giới", words:[
   ["本来","běnlái","vốn dĩ"],["并且","bìngqiě","và, hơn nữa"],["不过","búguò","nhưng, tuy nhiên"],["猜","cāi","đoán"],["吃惊","chī jīng","giật mình, ngạc nhiên"],["出现","chūxiàn","xuất hiện"],
   ["错误","cuòwù","sai lầm, lỗi"],["答案","dá'àn","đáp án"],["大概","dàgài","khoảng, có lẽ"],["到底","dàodǐ","rốt cuộc"],["而","ér","mà, còn"],["复杂","fùzá","phức tạp"],
   ["估计","gūjì","ước tính, đoán"],["好像","hǎoxiàng","hình như"],["怀疑","huáiyí","nghi ngờ"],["解释","jiěshì","giải thích"],["进行","jìnxíng","tiến hành"],["究竟","jiūjìng","rốt cuộc"],
   ["看法","kànfǎ","quan điểm"],["肯定","kěndìng","chắc chắn"],["难道","nándào","lẽ nào"],["判断","pànduàn","phán đoán"],["其中","qízhōng","trong đó"],["确实","quèshí","quả thực"],
   ["说明","shuōmíng","giải thích; cho thấy"],["相反","xiāngfǎn","ngược lại"],["也许","yěxǔ","có lẽ"],["以为","yǐwéi","tưởng rằng"],["正确","zhèngquè","đúng, chính xác"],["证明","zhèngmíng","chứng minh"],
   ["指","zhǐ","chỉ"],["准确","zhǔnquè","chính xác"]],
  sents:[{t:["你","猜","猜","答案","是","什么"],z:"你猜猜答案是什么？",p:"Nǐ cāicai dá'àn shì shénme?",v:"Bạn đoán xem đáp án là gì?"},{t:["我","以为","他","是","老师","原来","不","是"],z:"我以为他是老师，原来不是。",p:"Wǒ yǐwéi tā shì lǎoshī, yuánlái bú shì.",v:"Tôi tưởng anh ấy là giáo viên, hoá ra không phải."},{t:["这","个","问题","很","复杂","你","能","解释","一下","吗"],z:"这个问题很复杂，你能解释一下吗？",p:"Zhè ge wèntí hěn fùzá, nǐ néng jiěshì yíxià ma?",v:"Vấn đề này phức tạp, bạn giải thích được không?"},{t:["你","的","判断","是","正确","的"],z:"你的判断是正确的。",p:"Nǐ de pànduàn shì zhèngquè de.",v:"Phán đoán của bạn là đúng."}],
  write:["猜","案"]},
 {zh:"喝着茶看京剧", vi:"Vừa uống trà vừa xem Kinh kịch", words:[
   ["表演","biǎoyǎn","biểu diễn"],["参观","cānguān","tham quan"],["长城","Chángchéng","Vạn Lý Trường Thành"],["场","chǎng","buổi, trận"],["地点","dìdiǎn","địa điểm"],["干杯","gān bēi","cạn ly"],
   ["各","gè","các, mỗi"],["功夫","gōngfu","võ thuật; công sức"],["观众","guānzhòng","khán giả"],["激动","jīdòng","xúc động, phấn khích"],["饺子","jiǎozi","sủi cảo"],["京剧","jīngjù","Kinh kịch"],
   ["精彩","jīngcǎi","đặc sắc"],["举","jǔ","giơ, nâng"],["举办","jǔbàn","tổ chức"],["举行","jǔxíng","tổ chức, cử hành"],["烤鸭","kǎoyā","vịt quay"],["来自","láizì","đến từ"],
   ["民族","mínzú","dân tộc"],["热闹","rènao","náo nhiệt"],["首都","shǒudū","thủ đô"],["小吃","xiǎochī","món ăn vặt"],["兴奋","xīngfèn","hào hứng"],["演出","yǎnchū","biểu diễn; buổi diễn"],
   ["演员","yǎnyuán","diễn viên"],["邀请","yāoqǐng","mời"],["尤其","yóuqí","đặc biệt là"],["咱们","zánmen","chúng ta"],["著名","zhùmíng","nổi tiếng"],["专门","zhuānmén","chuyên, riêng"]],
  sents:[{t:["喝","着","茶","看","京剧"],z:"喝着茶看京剧。",p:"Hē zhe chá kàn jīngjù.",v:"Vừa uống trà vừa xem Kinh kịch."},{t:["这","场","演出","非常","精彩"],z:"这场演出非常精彩。",p:"Zhè chǎng yǎnchū fēicháng jīngcǎi.",v:"Buổi diễn này vô cùng đặc sắc."},{t:["咱们","去","北京","参观","长城","吧"],z:"咱们去北京参观长城吧。",p:"Zánmen qù Běijīng cānguān Chángchéng ba.",v:"Chúng ta đi Bắc Kinh thăm Trường Thành nhé."},{t:["我","最","喜欢","吃","北京","烤鸭"],z:"我最喜欢吃北京烤鸭。",p:"Wǒ zuì xǐhuan chī Běijīng kǎoyā.",v:"Tôi thích nhất vịt quay Bắc Kinh."}],
  write:["京","剧"]},
 {zh:"保护地球母亲", vi:"Bảo vệ Mẹ Trái Đất", words:[
   ["安全","ānquán","an toàn"],["保护","bǎohù","bảo vệ"],["表示","biǎoshì","bày tỏ, cho biết"],["部分","bùfen","phần, bộ phận"],["地球","dìqiú","trái đất"],["发生","fāshēng","xảy ra"],
   ["反对","fǎnduì","phản đối"],["规定","guīdìng","quy định"],["海洋","hǎiyáng","biển cả, đại dương"],["火","huǒ","lửa"],["减少","jiǎnshǎo","giảm bớt"],["节约","jiéyuē","tiết kiệm"],
   ["禁止","jìnzhǐ","cấm"],["空气","kōngqì","không khí"],["垃圾桶","lājītǒng","thùng rác"],["浪费","làngfèi","lãng phí"],["千万","qiānwàn","nhất định (phải / đừng)"],["情况","qíngkuàng","tình hình"],
   ["扔","rēng","ném, vứt"],["生命","shēngmìng","sự sống, sinh mạng"],["塑料袋","sùliàodài","túi ni-lông"],["所有","suǒyǒu","tất cả"],["危险","wēixiǎn","nguy hiểm"],["污染","wūrǎn","ô nhiễm"],
   ["因此","yīncǐ","vì vậy"],["引起","yǐnqǐ","gây ra"],["由于","yóuyú","do, bởi vì"],["增加","zēngjiā","tăng thêm"],["作用","zuòyòng","tác dụng"]],
  sents:[{t:["我们","要","保护","地球","母亲"],z:"我们要保护地球母亲。",p:"Wǒmen yào bǎohù dìqiú mǔqīn.",v:"Chúng ta phải bảo vệ Mẹ Trái Đất."},{t:["请","不","要","乱","扔","塑料袋"],z:"请不要乱扔塑料袋。",p:"Qǐng bú yào luàn rēng sùliàodài.",v:"Xin đừng vứt túi ni-lông bừa bãi."},{t:["这","里","的","空气","污染","很","严重"],z:"这里的空气污染很严重。",p:"Zhèlǐ de kōngqì wūrǎn hěn yánzhòng.",v:"Ô nhiễm không khí ở đây rất nặng."},{t:["我们","应该","节约","用","水","不","要","浪费"],z:"我们应该节约用水，不要浪费。",p:"Wǒmen yīnggāi jiéyuē yòng shuǐ, bú yào làngfèi.",v:"Chúng ta nên tiết kiệm nước, đừng lãng phí."}],
  write:["保","护"]},
 {zh:"教育孩子的艺术", vi:"Nghệ thuật dạy con", words:[
   ["棒","bàng","giỏi, tuyệt"],["笨","bèn","ngốc, chậm hiểu"],["表扬","biǎoyáng","khen ngợi"],["粗心","cūxīn","cẩu thả, sơ ý"],["对于","duìyú","đối với"],["儿童","értóng","trẻ em"],
   ["方法","fāngfǎ","phương pháp"],["放暑假","fàng shǔjià","nghỉ hè"],["鼓励","gǔlì","khích lệ"],["寒假","hánjià","kỳ nghỉ đông"],["活泼","huópō","hoạt bát"],["基础","jīchǔ","nền tảng"],
   ["骄傲","jiāo'ào","tự hào; kiêu ngạo"],["教授","jiàoshòu","giáo sư"],["教育","jiàoyù","giáo dục"],["礼貌","lǐmào","lễ phép"],["马虎","mǎhu","qua loa, đại khái"],["耐心","nàixīn","kiên nhẫn"],
   ["批评","pīpíng","phê bình"],["任何","rènhé","bất kỳ"],["使","shǐ","khiến, làm cho"],["是否","shìfǒu","có… hay không"],["受到","shòudào","nhận được, bị"],["橡皮","xiàngpí","cục tẩy"],
   ["学期","xuéqī","học kỳ"],["严格","yángé","nghiêm khắc"],["养成","yǎngchéng","hình thành (thói quen)"],["预习","yùxí","xem bài trước"],["允许","yǔnxǔ","cho phép"],["重视","zhòngshì","coi trọng"],
   ["自信","zìxìn","tự tin"]],
  sents:[{t:["教育","孩子","需要","耐心"],z:"教育孩子需要耐心。",p:"Jiàoyù háizi xūyào nàixīn.",v:"Dạy con cần kiên nhẫn."},{t:["老师","表扬","了","她","她","很","骄傲"],z:"老师表扬了她，她很骄傲。",p:"Lǎoshī biǎoyáng le tā, tā hěn jiāo'ào.",v:"Cô giáo khen bé, bé rất tự hào."},{t:["你","做","得","真","棒"],z:"你做得真棒！",p:"Nǐ zuò de zhēn bàng!",v:"Con làm giỏi quá!"},{t:["孩子","要","养成","预习","的","习惯"],z:"孩子要养成预习的习惯。",p:"Háizi yào yǎngchéng yùxí de xíguàn.",v:"Trẻ cần tạo thói quen xem bài trước."}],
  write:["教","育"]},
 {zh:"生活可以更美好", vi:"Cuộc sống có thể tốt đẹp hơn", words:[
   ["擦","cā","lau"],["厕所","cèsuǒ","nhà vệ sinh"],["厨房","chúfáng","nhà bếp"],["窗户","chuānghu","cửa sổ"],["倒","dào","đổ, rót; ngược"],["掉","diào","rơi; mất"],
   ["丢","diū","mất, đánh rơi"],["对面","duìmiàn","đối diện"],["房东","fángdōng","chủ nhà"],["挂","guà","treo"],["光","guāng","ánh sáng; hết sạch"],["家具","jiājù","đồ nội thất"],
   ["客厅","kètīng","phòng khách"],["空","kòng","chỗ trống; thời gian rảnh"],["拉","lā","kéo"],["懒","lǎn","lười"],["留","liú","để lại, ở lại"],["乱","luàn","lộn xộn, bừa"],
   ["弄","nòng","làm, khiến"],["敲","qiāo","gõ"],["沙发","shāfā","ghế sofa"],["师傅","shīfu","bác thợ, sư phụ"],["收拾","shōushi","dọn dẹp"],["顺便","shùnbiàn","tiện thể"],
   ["抬","tái","nâng, khiêng"],["推","tuī","đẩy"],["脱","tuō","cởi"],["卫生间","wèishēngjiān","nhà vệ sinh"],["响","xiǎng","kêu, reo"],["行","xíng","được, ổn"],
   ["钥匙","yàoshi","chìa khoá"],["意见","yìjiàn","ý kiến"],["脏","zāng","bẩn"],["整理","zhěnglǐ","sắp xếp, thu dọn"],["租","zū","thuê"]],
  sents:[{t:["我","的","房间","太","乱","了","要","收拾","一下"],z:"我的房间太乱了，要收拾一下。",p:"Wǒ de fángjiān tài luàn le, yào shōushi yíxià.",v:"Phòng tôi bừa quá, phải dọn một chút."},{t:["我","把","钥匙","弄","丢","了"],z:"我把钥匙弄丢了。",p:"Wǒ bǎ yàoshi nòng diū le.",v:"Tôi làm mất chìa khoá rồi."},{t:["我","在","客厅","里","擦","窗户"],z:"我在客厅里擦窗户。",p:"Wǒ zài kètīng li cā chuānghu.",v:"Tôi đang lau cửa sổ ở phòng khách."},{t:["我","在","学校","对面","租","了","一","个","房间"],z:"我在学校对面租了一个房间。",p:"Wǒ zài xuéxiào duìmiàn zū le yí ge fángjiān.",v:"Tôi thuê một phòng đối diện trường."}],
  write:["租","擦"]},
 {zh:"人与自然", vi:"Con người và thiên nhiên", words:[
   ["长江","Cháng Jiāng","sông Trường Giang"],["郊区","jiāoqū","ngoại ô"],["景色","jǐngsè","phong cảnh"],["竟然","jìngrán","vậy mà, không ngờ"],["棵","kē","cây (lượng từ)"],["可是","kěshì","nhưng"],
   ["老虎","lǎohǔ","con hổ"],["凉快","liángkuai","mát mẻ"],["暖和","nuǎnhuo","ấm áp"],["气候","qìhòu","khí hậu"],["森林","sēnlín","rừng"],["甚至","shènzhì","thậm chí"],
   ["死","sǐ","chết"],["温度","wēndù","nhiệt độ"],["无","wú","không có"],["许多","xǔduō","rất nhiều"],["亚洲","Yàzhōu","châu Á"],["叶子","yèzi","lá cây"],
   ["以","yǐ","lấy, dùng; để"],["于是","yúshì","thế là"],["与","yǔ","và, với"],["云","yún","mây"],["植物","zhíwù","thực vật"],["只好","zhǐhǎo","đành phải"],
   ["周围","zhōuwéi","xung quanh"],["座","zuò","(lượng từ: núi, cầu, toà nhà)"]],
  sents:[{t:["人","与","自然","的","关系","很","重要"],z:"人与自然的关系很重要。",p:"Rén yǔ zìrán de guānxi hěn zhòngyào.",v:"Quan hệ giữa con người và thiên nhiên rất quan trọng."},{t:["这","里","的","气候","很","暖和"],z:"这里的气候很暖和。",p:"Zhèlǐ de qìhòu hěn nuǎnhuo.",v:"Khí hậu ở đây rất ấm áp."},{t:["森林","里","有","许多","植物","和","动物"],z:"森林里有许多植物和动物。",p:"Sēnlín li yǒu xǔduō zhíwù hé dòngwù.",v:"Trong rừng có rất nhiều cây cối và động vật."},{t:["郊区","的","景色","很","美丽"],z:"郊区的景色很美丽。",p:"Jiāoqū de jǐngsè hěn měilì.",v:"Phong cảnh ngoại ô rất đẹp."}],
  write:["森","林"]},
 {zh:"科技与世界", vi:"Khoa học công nghệ và thế giới", words:[
   ["传真","chuánzhēn","fax"],["打印","dǎyìn","in"],["地址","dìzhǐ","địa chỉ"],["调查","diàochá","điều tra, khảo sát"],["短信","duǎnxìn","tin nhắn"],["发展","fāzhǎn","phát triển"],
   ["方式","fāngshì","cách thức"],["复印","fùyìn","photo, sao chụp"],["广播","guǎngbō","phát thanh"],["国际","guójì","quốc tế"],["号码","hàomǎ","số (điện thoại…)"],["互联网","hùliánwǎng","internet"],
   ["记者","jìzhě","phóng viên"],["技术","jìshù","kỹ thuật, công nghệ"],["寄","jì","gửi (thư, hàng)"],["科学","kēxué","khoa học"],["密码","mìmǎ","mật khẩu"],["秒","miǎo","giây"],
   ["使用","shǐyòng","sử dụng"],["世纪","shìjì","thế kỷ"],["数字","shùzì","chữ số"],["速度","sùdù","tốc độ"],["随着","suízhe","cùng với, theo"],["台","tái","(lượng từ máy móc)"],
   ["提供","tígōng","cung cấp"],["网站","wǎngzhàn","trang web"],["详细","xiángxì","chi tiết"],["消息","xiāoxi","tin tức"],["信封","xìnfēng","phong bì"],["信息","xìnxī","thông tin"],
   ["研究","yánjiū","nghiên cứu"],["由","yóu","do, bởi"],["邮局","yóujú","bưu điện"],["占线","zhàn xiàn","máy bận"]],
  sents:[{t:["科学","技术","发展","得","很","快"],z:"科学技术发展得很快。",p:"Kēxué jìshù fāzhǎn de hěn kuài.",v:"Khoa học kỹ thuật phát triển rất nhanh."},{t:["我","忘记","了","手机","的","密码"],z:"我忘记了手机的密码。",p:"Wǒ wàngjì le shǒujī de mìmǎ.",v:"Tôi quên mật khẩu điện thoại rồi."},{t:["我","打电话","给","他","一直","占线"],z:"我打电话给他，一直占线。",p:"Wǒ dǎ diànhuà gěi tā, yìzhí zhàn xiàn.",v:"Tôi gọi cho anh ấy, máy cứ bận mãi."},{t:["请","把","你","的","地址","发","给","我"],z:"请把你的地址发给我。",p:"Qǐng bǎ nǐ de dìzhǐ fā gěi wǒ.",v:"Hãy gửi địa chỉ của bạn cho tôi."}],
  write:["技","术"]},
 {zh:"生活的味道", vi:"Hương vị cuộc sống", words:[
   ["包子","bāozi","bánh bao"],["餐厅","cāntīng","nhà hàng"],["刀","dāo","con dao"],["果汁","guǒzhī","nước ép"],["可惜","kěxī","tiếc là"],["苦","kǔ","đắng; khổ"],
   ["辣","là","cay"],["连","lián","ngay cả; liền"],["内","nèi","trong, bên trong"],["葡萄","pútao","nho"],["其次","qícì","tiếp theo, thứ hai"],["稍微","shāowēi","hơi, một chút"],
   ["勺子","sháozi","cái thìa"],["剩","shèng","còn thừa"],["首先","shǒuxiān","trước hết"],["酸","suān","chua"],["随便","suíbiàn","tùy ý"],["汤","tāng","canh, súp"],
   ["糖","táng","đường, kẹo"],["同时","tóngshí","đồng thời"],["味道","wèidao","mùi vị"],["西红柿","xīhóngshì","cà chua"],["咸","xián","mặn"],["香","xiāng","thơm"],
   ["盐","yán","muối"],["正好","zhènghǎo","vừa đúng"],["仔细","zǐxì","tỉ mỉ, cẩn thận"]],
  sents:[{t:["生活","的","味道","有","酸","有","甜"],z:"生活的味道有酸有甜。",p:"Shēnghuó de wèidao yǒu suān yǒu tián.",v:"Hương vị cuộc sống có chua có ngọt."},{t:["这","个","汤","太","咸","了"],z:"这个汤太咸了。",p:"Zhè ge tāng tài xián le.",v:"Món canh này mặn quá."},{t:["你","喜欢","吃","辣","的","吗"],z:"你喜欢吃辣的吗？",p:"Nǐ xǐhuan chī là de ma?",v:"Bạn có thích ăn cay không?"},{t:["西红柿","鸡蛋","汤","的","味道","很","香"],z:"西红柿鸡蛋汤的味道很香。",p:"Xīhóngshì jīdàn tāng de wèidao hěn xiāng.",v:"Canh cà chua trứng rất thơm."}],
  write:["酸","辣"]},
 {zh:"路上的风景", vi:"Phong cảnh trên đường", words:[
   ["乘坐","chéngzuò","đi (tàu, xe, máy bay)"],["出发","chūfā","xuất phát"],["打招呼","dǎ zhāohu","chào hỏi"],["大使馆","dàshǐguǎn","đại sứ quán"],["导游","dǎoyóu","hướng dẫn viên"],["到处","dàochù","khắp nơi"],
   ["登机牌","dēngjīpái","thẻ lên máy bay"],["堵车","dǔ chē","tắc đường"],["方向","fāngxiàng","phương hướng"],["赶","gǎn","đuổi kịp; vội"],["高速公路","gāosù gōnglù","đường cao tốc"],["公里","gōnglǐ","ki-lô-mét"],
   ["国籍","guójí","quốc tịch"],["航班","hángbān","chuyến bay"],["加油站","jiāyóuzhàn","trạm xăng"],["降落","jiàngluò","hạ cánh"],["交通","jiāotōng","giao thông"],["警察","jǐngchá","cảnh sát"],
   ["来不及","láibují","không kịp"],["来得及","láidejí","kịp"],["旅行","lǚxíng","du lịch"],["迷路","mí lù","lạc đường"],["签证","qiānzhèng","visa, thị thực"],["桥","qiáo","cây cầu"],
   ["入口","rùkǒu","lối vào"],["趟","tàng","chuyến, lượt"],["停","tíng","dừng"],["推迟","tuīchí","hoãn lại"],["直接","zhíjiē","trực tiếp, thẳng"],["转","zhuǎn","chuyển, rẽ"],
   ["准时","zhǔnshí","đúng giờ"],["座位","zuòwèi","chỗ ngồi"]],
  sents:[{t:["我们","明天","早上","八","点","出发"],z:"我们明天早上八点出发。",p:"Wǒmen míngtiān zǎoshang bā diǎn chūfā.",v:"Sáng mai 8 giờ chúng ta xuất phát."},{t:["路","上","堵车","了","我","来不及","了"],z:"路上堵车了，我来不及了。",p:"Lù shang dǔ chē le, wǒ láibují le.",v:"Đường tắc rồi, tôi không kịp mất."},{t:["航班","推迟","了","两","个","小时"],z:"航班推迟了两个小时。",p:"Hángbān tuīchí le liǎng ge xiǎoshí.",v:"Chuyến bay bị hoãn hai tiếng."},{t:["我","在","北京","迷路","了"],z:"我在北京迷路了。",p:"Wǒ zài Běijīng mí lù le.",v:"Tôi bị lạc đường ở Bắc Kinh."}],
  write:["旅","行"]},
 {zh:"复习", vi:"Ôn tập cả sách", review:true, words:[], sents:[], write:[]}
];
const EXTRA_PY = { };
