# Nội dung "Xem chi tiết lớp" (popup) cho 9 lớp — 3 thứ tiếng.
# Không ghi giá, không ghi lịch cụ thể (chị Linh chốt 19/09/2026).
# Mỗi lớp: fit (phù hợp với), out (sau khoá con làm được), how (một buổi học), cls (lớp học), faq [(hỏi, đáp)]

H = {
 'vi': dict(fit='Phù hợp với', out='Sau khoá, con có thể', how='Một buổi học', cls='Lớp học', faq='Ba mẹ hay hỏi',
            note='Lịch học và học phí: SunMoon tư vấn riêng theo tuổi và trình độ của con.',
            more='Xem chi tiết lớp', out_adult='Sau khoá, bạn có thể'),
 'en': dict(fit='Right for', out='After the course, your child can', how='A typical lesson', cls='Class format', faq='Parents often ask',
            note='Schedule and fees: SunMoon advises you personally based on age and level.',
            more='See class details', out_adult='After the course, you can'),
 'zh': dict(fit='适合', out='学完后，孩子能够', how='一节课的安排', cls='班级形式', faq='家长常问',
            note='上课时间与学费：日月会根据孩子的年龄和水平单独为您介绍。',
            more='查看课程详情', out_adult='学完后，您能够'),
}

C = {
'little': {
 'adult': False,
 'vi': dict(
  tag=['Tiếng Trung đầu tiên của con không bắt đầu từ chữ viết.', 'Mà bắt đầu từ việc nghe, chơi và dám nói.'],
  fit=['Bé <b>3–7 tuổi</b>, mới bắt đầu làm quen với tiếng Trung', 'Bé chưa biết chữ Hán, <b>chưa cần biết Pinyin</b>', 'Đặc biệt phù hợp với những bé cần một môi trường học <b>nhẹ nhàng, nhiều tương tác và không áp lực</b>'],
  t_out='Sau mỗi giai đoạn, con sẽ từng bước',
  out=['<b>Nghe hiểu</b> những câu nói và chỉ dẫn quen thuộc', 'Bắt đầu <b>chủ động nói</b> những từ và câu đơn giản bằng tiếng Trung', 'Tích luỹ vốn từ gần gũi: màu sắc, con vật, gia đình, đồ ăn, đồ chơi…', 'Có thể hát, kể lại những câu chuyện ngắn bằng tiếng Trung', 'Quan trọng nhất: con thấy tiếng Trung <b>thật vui và không ngại mở lời</b>'],
  t_how='Một buổi học của con',
  how_intro='Mỗi buổi học là một khoảng thời gian để con vừa chơi, vừa khám phá và tự nhiên sử dụng tiếng Trung.',
  how=['Khởi động bằng bài hát và vận động', 'Làm quen từ mới qua hình ảnh, đồ vật thật và tình huống quen thuộc', 'Học qua trò chơi, tương tác và kể chuyện', 'Thực hành nói trong những tình huống gần gũi với con', 'Xen kẽ các hoạt động tô màu, vẽ, thủ công để giữ sự tập trung và hứng thú'],
  how_outro='Không ép con học thuộc. Không bắt con ngồi yên quá lâu.<br>Mỗi hoạt động đều được thiết kế để con có lý do muốn nói tiếng Trung.',
  t_cls='Lớp học nhỏ — để con được quan tâm đủ nhiều',
  cls=['Lớp <b>tối đa 6 bé</b>', 'Giáo viên theo sát từng bé trong suốt buổi học', 'Quan sát khả năng tiếp thu và mức độ tương tác của từng con', 'Sau buổi học, ba mẹ nhận được <b>nhận xét riêng về con</b>: con đã làm tốt điều gì, đang gặp khó khăn ở đâu và cần tiếp tục rèn luyện điều gì'],
  faq=[('Con chưa biết gì về tiếng Trung có học được không?', 'Có. SunMoon PreChinese được thiết kế cho những bé bắt đầu từ con số 0. Con chưa cần biết chữ Hán hay Pinyin. Giai đoạn đầu, con sẽ làm quen với tiếng Trung thông qua nghe, hình ảnh, vận động, trò chơi và giao tiếp.'),
       ('Con nhút nhát, ít nói thì sao?', 'Không sao cả. Chúng tôi không đặt mục tiêu bắt con phải nói ngay. Giáo viên sẽ tạo cơ hội để con làm quen, quan sát, tham gia và dần dần mở lời theo nhịp độ của mình.'),
       ('Con học thử như thế nào?', 'Con vào học cùng lớp 1 buổi. Sau buổi học, cô gửi ba mẹ nhận xét và gợi ý lớp phù hợp với con.'),
       ('Làm sao ba mẹ biết con tiến bộ?', 'Sau mỗi buổi học, ba mẹ nhận nhận xét riêng: con đã làm tốt điều gì, đang gặp khó khăn ở đâu và cần rèn thêm điều gì.'),
       ('Con nghỉ học thì có được học bù không?', 'Có. Ba mẹ báo trước với SunMoon, con sẽ được xếp buổi học bù hoặc bảo lưu buổi nghỉ.'),
       ('Ba mẹ không biết tiếng Trung thì kèm con ở nhà thế nào?', 'Không cần biết tiếng Trung. Cô gợi ý bài hát, trò chơi nhỏ để ba mẹ cùng con ôn lại ở nhà.'),
       ('Học xong PreChinese, con học tiếp lớp nào?', 'Con lên lớp SunMoon ChineseKids (7–13 tuổi) để học nghe, nói, đọc, viết bài bản hơn.'),
       ('Lớp học ở đâu?', 'Tại P1 và L6, khu Vinhomes Central Park, 208 Nguyễn Hữu Cảnh, Bình Thạnh.')],
  note='Lịch học và học phí: SunMoon tư vấn riêng theo độ tuổi, khả năng và nhu cầu của từng bé.'),
 'en': dict(
  tag=["Your child's first Chinese doesn't start with writing.", 'It starts with listening, playing and daring to speak.'],
  fit=['Children <b>aged 3–7</b> just starting Chinese', 'No Chinese characters and <b>no pinyin needed</b>', 'Especially suited to children who need a <b>gentle, interactive, pressure-free</b> setting'],
  t_out='Stage by stage, your child will',
  out=['<b>Understand</b> familiar phrases and instructions', 'Begin to <b>speak up</b> with simple words and sentences in Chinese', 'Build everyday vocabulary: colours, animals, family, food, toys…', 'Sing and retell short stories in Chinese', 'Most importantly: find Chinese <b>fun and not be afraid to speak</b>'],
  t_how="Your child's lesson",
  how_intro='Each lesson is time to play, explore and use Chinese naturally.',
  how=['Warm-up with songs and movement', 'New words through pictures, real objects and familiar situations', 'Learning through games, interaction and storytelling', 'Speaking practice in situations close to their daily life', 'Colouring, drawing and crafts in between to keep focus and interest'],
  how_outro='No rote memorising. No sitting still for too long.<br>Every activity is designed to give your child a reason to speak Chinese.',
  t_cls='Small classes — so every child gets enough attention',
  cls=['<b>Max 6 children</b> per class', 'The teacher follows each child throughout the lesson', "Observing each child's progress and engagement", 'After class, parents receive <b>personal feedback</b>: what your child did well, where they struggle and what to keep practising'],
  faq=[('My child knows no Chinese at all. Can they join?', 'Yes. SunMoon PreChinese is designed for children starting from zero. No characters or pinyin needed. At first, children get to know Chinese through listening, pictures, movement, games and conversation.'),
       ('My child is shy and quiet. Is that OK?', "Absolutely. We don't push children to speak straight away. The teacher gives them chances to get used to it, watch, join in and gradually speak at their own pace."),
       ('How does the trial lesson work?', 'Your child joins the class for one lesson. Afterwards, the teacher sends you feedback and suggests the right class.'),
       ("How will I know my child is progressing?", 'After every lesson you receive personal feedback: what your child did well, where they struggle and what to practise next.'),
       ('If my child misses a lesson, can they make it up?', 'Yes. Let SunMoon know in advance and your child will get a make-up lesson or the lesson will be saved for later.'),
       ("I don't speak Chinese. How can I help at home?", 'No Chinese needed. The teacher suggests songs and small games you can enjoy together at home.'),
       ('What comes after PreChinese?', 'Your child moves up to SunMoon ChineseKids (ages 7–13) for structured listening, speaking, reading and writing.'),
       ('Where are the classes?', 'At P1 and L6, Vinhomes Central Park, 208 Nguyen Huu Canh, Binh Thanh.')],
  note="Schedule and fees: SunMoon advises you personally based on your child's age, ability and needs."),
 'zh': dict(
  tag=['孩子的第一句中文，不是从写字开始的。', '而是从听、玩和敢于开口开始。'],
  fit=['<b>3–7 岁</b>、刚开始接触中文的孩子', '还不认识汉字，<b>也不需要会拼音</b>', '特别适合需要<b>轻松、多互动、无压力</b>学习环境的孩子'],
  t_out='每个阶段，孩子会一步步',
  out=['<b>听懂</b>熟悉的句子和指令', '开始<b>主动说出</b>简单的中文词语和句子', '积累身边的词汇：颜色、动物、家人、食物、玩具……', '能用中文唱儿歌、复述小故事', '最重要的是：孩子觉得中文<b>很有趣，不怕开口</b>'],
  t_how='孩子的一节课',
  how_intro='每节课都是孩子边玩、边探索、自然使用中文的时光。',
  how=['儿歌和律动热身', '通过图片、实物和熟悉的情境认识新词', '在游戏、互动和故事中学习', '在贴近生活的情境中练习说话', '穿插涂色、画画、手工，保持专注和兴趣'],
  how_outro='不逼孩子死记硬背，也不让孩子久坐不动。<br>每个活动都让孩子有想说中文的理由。',
  t_cls='小班教学 — 让每个孩子得到足够关注',
  cls=['每班<b>最多 6 名孩子</b>', '老师全程关注每一个孩子', '观察每个孩子的接受能力和互动程度', '课后家长会收到<b>孩子的个人点评</b>：做得好的地方、遇到的困难以及需要继续练习的内容'],
  faq=[('孩子完全不懂中文可以学吗？', '可以。SunMoon PreChinese 专为零基础的孩子设计，不需要认识汉字或拼音。起步阶段，孩子通过听、图片、律动、游戏和交流来熟悉中文。'),
       ('孩子比较内向、话少怎么办？', '没关系。我们不要求孩子马上开口。老师会给孩子机会慢慢熟悉、观察、参与，按照自己的节奏开口。'),
       ('试听课怎么安排？', '孩子跟班上一节课。课后老师会给家长点评，并推荐适合的班级。'),
       ('家长怎么知道孩子的进步？', '每节课后家长都会收到个人点评：孩子做得好的地方、遇到的困难以及需要继续练习的内容。'),
       ('孩子请假可以补课吗？', '可以。请提前告知日月，孩子可以安排补课或保留该节课。'),
       ('家长不会中文，在家怎么陪孩子？', '不需要会中文。老师会推荐儿歌和小游戏，方便家长在家陪孩子复习。'),
       ('学完 PreChinese 后接着学什么？', '孩子可以升入 SunMoon ChineseKids（7–13 岁），系统学习听说读写。'),
       ('在哪里上课？', '在 Vinhomes Central Park 的 P1 和 L6，地址：208 Nguyễn Hữu Cảnh，平盛郡。')],
  note='上课时间与学费：日月会根据每个孩子的年龄、能力和需求单独为您介绍。'),
},
'kids': {
 'adult': False,
 'vi': dict(
  tag=['Tiếng Trung cho trẻ em — học đúng nền tảng, tiến bộ từng bước.'],
  lead='Dành cho các bé từ 7–13 tuổi, từ mới bắt đầu đến đã có nền tảng cơ bản và muốn học tiếng Trung bài bản hơn.',
  t_out='Con sẽ học được gì?',
  out_intro='Không chỉ học thuộc từ vựng, con được phát triển đồng đều cả 4 kỹ năng:',
  out=['<b>Nghe – Nói</b>: giao tiếp qua những chủ đề gần gũi với cuộc sống của trẻ', '<b>Đọc</b>: đọc pinyin, từ và câu theo từng cấp độ', '<b>Viết</b>: làm quen, nhận diện và luyện viết chữ Hán đúng nét', '<b>Giao tiếp</b>: sử dụng từ và mẫu câu đã học vào tình huống thực tế'],
  out_outro='Từ nền tảng này, con có thể tiếp tục theo lộ trình HSK khi phù hợp.',
  t_how='Mỗi buổi học có gì?',
  how_intro='Một buổi học được thiết kế để con được nói, được thực hành và được ghi nhớ qua trải nghiệm, thay vì chỉ ngồi học thuộc.',
  steps=[('Khởi động', 'Ôn lại bài cũ bằng trò chơi và hoạt động ngắn.'), ('Học chủ đề mới', 'Từ vựng và mẫu câu được đưa vào những chủ đề gần gũi với độ tuổi của con.'), ('Thực hành giao tiếp', 'Luyện nói theo cặp, nhóm nhỏ và các tình huống thực tế.'), ('Đọc & viết', 'Luyện đọc pinyin, nhận diện chữ Hán và từng bước hình thành khả năng viết.'), ('Củng cố tại nhà', 'Bài tập vừa sức để con ôn lại kiến thức mà không cảm thấy quá tải.')],
  t_cls='Lớp học nhỏ — để con được học thật',
  cls=['<b>Tối đa 6 bé/lớp</b>', 'Xếp lớp dựa trên độ tuổi và trình độ thực tế', 'Có buổi học thử để giáo viên quan sát khả năng của con', 'Sau buổi học, ba mẹ nhận nhận xét riêng về tình hình học tập của con'],
  t_faq='Ba mẹ thường hỏi',
  faq=[('Con đã từng học tiếng Trung ở nơi khác thì sao?', 'Không cần bắt đầu lại từ đầu. SunMoon sẽ đánh giá nền tảng hiện tại để tư vấn cấp độ phù hợp với con.'),
       ('Con có bài tập về nhà không?', 'Có, nhưng được thiết kế vừa sức và phù hợp với độ tuổi, mục tiêu là giúp con duy trì việc tiếp xúc với tiếng Trung mà không tạo áp lực.'),
       ('Con chưa biết gì về tiếng Trung có học được không?', 'Hoàn toàn được. Bé mới bắt đầu sẽ được xây nền từ phát âm, pinyin, từ vựng và những mẫu câu đầu tiên.')],
  t_note='Bắt đầu từ đúng trình độ của con',
  note='Lịch học và học phí được SunMoon tư vấn riêng theo độ tuổi, trình độ và mục tiêu học tập của từng bé.'),
 'en': dict(
  tag=['Chinese for children — the right foundation, steady progress.'],
  lead='For children aged 7–13, from complete beginners to those with some basics who want a more structured way to learn Chinese.',
  t_out='What will your child learn?',
  out_intro='More than memorising words, your child develops all four skills evenly:',
  out=['<b>Listening & speaking</b>: conversations on topics close to children\'s lives', '<b>Reading</b>: pinyin, words and sentences level by level', '<b>Writing</b>: recognising and writing Chinese characters with correct strokes', '<b>Communication</b>: using words and patterns in real situations'],
  out_outro='From this foundation, your child can move on to the HSK pathway when ready.',
  t_how="What's in each lesson?",
  how_intro='Each lesson is designed so children speak, practise and remember through experience, not just rote learning.',
  steps=[('Warm-up', 'Review the last lesson with games and short activities.'), ('New topic', 'Words and sentence patterns in topics suited to their age.'), ('Speaking practice', 'Pair work, small groups and real-life situations.'), ('Reading & writing', 'Pinyin reading, character recognition and step-by-step writing.'), ('Practice at home', 'Manageable homework to review without overload.')],
  t_cls='Small classes — so children really learn',
  cls=['<b>Max 6 children per class</b>', 'Placed by age and actual level', 'A trial lesson lets the teacher see your child\'s level', 'After class, parents receive personal feedback on progress'],
  t_faq='Parents often ask',
  faq=[('My child studied Chinese elsewhere. Do they start over?', "No need. SunMoon assesses your child's current level and recommends the right class."),
       ('Is there homework?', "Yes, but it's age-appropriate and manageable — enough to keep in touch with Chinese without pressure."),
       ('My child knows no Chinese. Can they join?', 'Absolutely. Beginners build a foundation in pronunciation, pinyin, vocabulary and first sentence patterns.')],
  t_note="Start at your child's level",
  note="Schedule and fees: SunMoon advises you personally based on your child's age, level and learning goals."),
 'zh': dict(
  tag=['少儿中文——打好基础，一步步进步。'],
  lead='适合 7–13 岁的孩子，无论零基础还是已有一定基础、希望更系统地学习中文。',
  t_out='孩子能学到什么？',
  out_intro='不只是背单词，孩子的四项技能会全面均衡发展：',
  out=['<b>听说</b>：围绕贴近孩子生活的话题交流', '<b>阅读</b>：按级别读拼音、词语和句子', '<b>书写</b>：认识汉字并按正确笔顺练写', '<b>交际</b>：把学过的词语和句型用在真实情境中'],
  out_outro='在此基础上，孩子可在合适的时候继续 HSK 进阶之路。',
  t_how='每节课有什么？',
  how_intro='每节课都让孩子多说、多练，在体验中记住，而不是死记硬背。',
  steps=[('热身', '用游戏和小活动复习上节课内容。'), ('学习新主题', '在符合孩子年龄的主题中学习词语和句型。'), ('交际练习', '两人、小组练习以及真实情境对话。'), ('读与写', '练读拼音、认读汉字，逐步培养书写能力。'), ('在家巩固', '适量作业，复习不负担。')],
  t_cls='小班教学——让孩子真正学到',
  cls=['<b>每班最多 6 名孩子</b>', '根据年龄和实际水平分班', '安排试听课，老师了解孩子的能力', '课后家长会收到孩子学习情况的个人点评'],
  t_faq='家长常问',
  faq=[('孩子在别处学过中文怎么办？', '不需要从头开始。日月会评估孩子现有基础，推荐合适的级别。'),
       ('有家庭作业吗？', '有，但分量适中、符合年龄，目的是让孩子保持接触中文而不增加压力。'),
       ('孩子完全不懂中文可以学吗？', '完全可以。零基础的孩子会从发音、拼音、词汇和第一批句型开始打基础。')],
  t_note='从孩子真正的水平开始',
  note='上课时间与学费：日月会根据每个孩子的年龄、水平和学习目标单独为您介绍。'),
},
'work': {
 'adult': True,
 'vi': dict(
  kicker='Người lớn · Business Chinese',
  tag=['Học tiếng Trung từ chính công việc bạn đang làm.'],
  lead='Dành cho người đi làm, chủ doanh nghiệp và người thường xuyên làm việc với đối tác Trung Quốc — đặc biệt khi công việc liên quan đến nhập hàng, kinh doanh, bán hàng, đàm phán hoặc chăm sóc khách hàng.<br><br>Tại SunMoon, nội dung học không đi theo một giáo trình cố định cho tất cả mọi người. Chúng tôi bắt đầu từ công việc thực tế của bạn và xây dựng nội dung phù hợp với nhu cầu sử dụng.',
  t_out='Bạn sẽ dùng được gì?',
  out_intro='Sau khoá học, bạn có thể từng bước sử dụng tiếng Trung để:',
  out=['Trao đổi giá, thương lượng và chốt đơn', 'Hỏi hàng, đặt hàng, theo dõi tiến độ và xử lý đơn', 'Nhắn tin với khách hàng, đối tác, nhà cung cấp', 'Viết những nội dung công việc cơ bản bằng tiếng Trung', 'Sử dụng từ vựng và thuật ngữ đúng với ngành nghề', 'Gọi điện, trao đổi trực tiếp và tham gia các cuộc gặp với đối tác'],
  t_how='Mỗi buổi học — một tình huống thực tế',
  how_intro='Không chỉ học từ vựng và ngữ pháp trên sách.<br>Bài học được xây dựng từ những tình huống bạn thực sự gặp trong công việc:',
  steps=[('Tình huống', 'Xuất phát từ một vấn đề hoặc nhu cầu giao tiếp thực tế.'), ('Từ vựng & mẫu câu', 'Học đúng những từ và cách diễn đạt cần dùng.'), ('Thực hành', 'Đóng vai khách hàng – nhà cung cấp – đối tác để luyện phản xạ.'), ('Ứng dụng', 'Đưa tình huống về đúng công việc của bạn để có thể sử dụng ngay sau buổi học.')],
  extra=[('Có thể học theo ngành của bạn', 'Nội dung có thể điều chỉnh theo lĩnh vực bạn đang làm, chẳng hạn:', ['Xuất nhập khẩu · Đặt hàng · Logistics', 'Kinh doanh · Sales · Chăm sóc khách hàng', 'Bất động sản', 'Thương mại & sản xuất', 'Nhà hàng · Dịch vụ · Du lịch', 'Hoặc ngành nghề riêng của bạn'])],
  t_forms='Hình thức học',
  forms=[('1 kèm 1', 'Lộ trình được thiết kế riêng theo công việc, trình độ và mục tiêu của bạn.'), ('Nhóm nhỏ', 'Học cùng những người có nhu cầu tương đồng, tăng thời lượng thực hành và phản xạ giao tiếp.')],
  faq=[],
  t_note='Không học tiếng Trung chỉ để biết.', note_lead='Học để dùng được trong công việc.',
  note='Lịch học và học phí được SunMoon tư vấn dựa trên trình độ hiện tại, ngành nghề và mục tiêu sử dụng tiếng Trung của bạn.',
  reg='Đăng ký tư vấn / học thử', ask='Nhắn Zalo cho SunMoon'),
 'en': dict(
  kicker='Adults · Business Chinese',
  tag=['Learn Chinese from the work you actually do.'],
  lead='For professionals, business owners and anyone who works with Chinese partners — especially in sourcing, trading, sales, negotiation or customer service.<br><br>At SunMoon, there is no fixed textbook for everyone. We start from your real work and build content around what you need to use.',
  t_out='What will you be able to do?',
  out_intro='After the course, you can gradually use Chinese to:',
  out=['Discuss prices, negotiate and close deals', 'Ask about products, place orders, track progress and handle orders', 'Message customers, partners and suppliers', 'Write basic work content in Chinese', 'Use the right vocabulary and terms for your industry', 'Make calls, talk face to face and join partner meetings'],
  t_how='Every lesson — a real situation',
  how_intro='Not just vocabulary and grammar from a book.<br>Lessons are built from situations you actually face at work:',
  steps=[('Situation', 'Start from a real problem or communication need.'), ('Words & phrases', 'Learn exactly the words and expressions you need.'), ('Practice', 'Role-play customer – supplier – partner to build reflexes.'), ('Application', 'Bring the situation back to your own work so you can use it right after class.')],
  extra=[('Tailored to your industry', 'Content can be adapted to your field, for example:', ['Import–export · Ordering · Logistics', 'Business · Sales · Customer service', 'Real estate', 'Trade & manufacturing', 'Restaurants · Services · Tourism', 'Or your own industry'])],
  t_forms='Class format',
  forms=[('One-to-one', 'A pathway designed around your work, level and goals.'), ('Small group', 'Learn with people who have similar needs, with more speaking practice.')],
  faq=[],
  t_note="Don't learn Chinese just to know it.", note_lead='Learn it to use at work.',
  note='SunMoon advises on schedule and fees based on your current level, industry and goals.',
  reg='Request advice / a trial lesson', ask='Message SunMoon on Zalo'),
 'zh': dict(
  kicker='成人 · 商务中文',
  tag=['从您正在做的工作中学中文。'],
  lead='适合职场人士、企业主以及经常与中国伙伴打交道的人——尤其是从事采购、经营、销售、谈判或客户服务的工作。<br><br>在日月，我们不用一套固定教材教所有人，而是从您的实际工作出发，按使用需求设计学习内容。',
  t_out='您能用中文做什么？',
  out_intro='学完后，您可以逐步用中文：',
  out=['谈价格、议价并成交', '询货、下单、跟进进度并处理订单', '与客户、伙伴、供应商沟通消息', '用中文写基本的工作内容', '使用本行业的正确词汇和术语', '打电话、面对面交流并参加与伙伴的会议'],
  t_how='每节课——一个真实情境',
  how_intro='不只是书本上的词汇和语法。<br>课程来自您在工作中真正遇到的情境：',
  steps=[('情境', '从一个真实的问题或沟通需求出发。'), ('词汇与句型', '学习真正需要的词语和表达方式。'), ('练习', '扮演客户—供应商—伙伴，训练反应。'), ('应用', '把情境带回您的工作，课后马上就能用。')],
  extra=[('按您的行业学习', '内容可根据您所在的领域调整，例如：', ['进出口 · 订货 · 物流', '经营 · 销售 · 客户服务', '房地产', '贸易与生产', '餐饮 · 服务 · 旅游', '或您自己的行业'])],
  t_forms='上课形式',
  forms=[('一对一', '按您的工作、水平和目标量身设计学习路径。'), ('小组', '与需求相近的人一起学习，增加练习和口语反应。')],
  faq=[],
  t_note='学中文，不只是为了知道。', note_lead='而是为了在工作中用得上。',
  note='上课时间与学费：日月会根据您的现有水平、行业和使用目标为您介绍。',
  reg='预约咨询 / 试听', ask='Zalo 联系日月'),
},
'custom': {
 'adult': True,
 'vi': dict(
  kicker='Theo nhu cầu · Personalised Classes',
  tag=['Lớp học được thiết kế cho riêng bạn'],
  lead='Không phải ai cũng cần học cùng một lộ trình.<br>Mỗi người có một mục tiêu, một nền tảng và một quỹ thời gian khác nhau.<br><br>SunMoon xây dựng chương trình học dựa trên điểm xuất phát và mục tiêu thực tế của từng học viên — từ học nhanh để giao tiếp, chuẩn bị du học, phục vụ công việc đến củng cố những phần kiến thức còn thiếu.',
  fit=['Người có mục tiêu học tập riêng: du học, công việc, thi cử, giao tiếp…', 'Người cần học cấp tốc cho một nhu cầu cụ thể', 'Người bận rộn, cần lịch học linh hoạt', 'Học viên muốn tập trung vào một kỹ năng hoặc chủ đề nhất định', 'Trẻ cần kèm riêng, củng cố hoặc bù đắp kiến thức'],
  out=[],
  t_how='Mỗi lộ trình bắt đầu từ bạn',
  steps=[('Hiểu mục tiêu', 'Giáo viên trao đổi để hiểu trình độ hiện tại, nhu cầu và thời gian bạn có thể dành cho việc học.'), ('Thiết kế lộ trình', 'Nội dung, tốc độ và tài liệu được điều chỉnh theo mục tiêu riêng.'), ('Học & thực hành', 'Tập trung vào những kiến thức và kỹ năng bạn thực sự cần sử dụng.'), ('Theo dõi & điều chỉnh', 'Đánh giá tiến bộ theo từng giai đoạn và thay đổi nội dung khi mục tiêu hoặc nhu cầu của bạn thay đổi.')],
  t_forms='Linh hoạt về hình thức',
  forms=[('1 kèm 1', 'Toàn bộ thời lượng và nội dung tập trung vào một học viên.'), ('Nhóm nhỏ', 'Có thể học cùng bạn bè, người thân hoặc nhóm có cùng mục tiêu.'), ('Online / Offline', 'Lựa chọn hình thức học phù hợp với lịch trình và nhu cầu của bạn.')],
  t_faq='Ba mẹ thường hỏi',
  faq=[('Học online được không?', 'Có. Nội dung và cách triển khai được điều chỉnh để phù hợp với hình thức học online.'),
       ('Có được lựa chọn giáo viên không?', 'SunMoon sẽ tư vấn giáo viên dựa trên độ tuổi, trình độ, mục tiêu và phong cách học của học viên.'),
       ('Có thể thay đổi nội dung trong quá trình học không?', 'Có. Lộ trình được theo dõi và điều chỉnh theo tiến độ thực tế.')],
  t_note='Một lộ trình riêng. Một tốc độ riêng.',
  note='Lịch học và học phí được SunMoon tư vấn dựa trên mục tiêu, trình độ và hình thức học của từng học viên.',
  reg='Đăng ký tư vấn / học thử', ask='Nhắn Zalo cho SunMoon'),
 'en': dict(
  kicker='Tailored · Personalised Classes',
  tag=['A class designed just for you'],
  lead="Not everyone needs the same pathway.<br>Everyone has different goals, a different starting point and different amounts of time.<br><br>SunMoon builds each programme around the learner's real starting point and goals — from fast-track conversation and study-abroad preparation to Chinese for work or filling knowledge gaps.",
  fit=['Learners with their own goals: study abroad, work, exams, conversation…', 'Anyone who needs an intensive course for a specific need', 'Busy people who need a flexible schedule', 'Learners who want to focus on one skill or topic', 'Children who need one-to-one support or catch-up'],
  out=[],
  t_how='Every pathway starts with you',
  steps=[('Understand your goals', 'The teacher talks with you about your current level, needs and the time you can give.'), ('Design the pathway', 'Content, pace and materials adjusted to your goals.'), ('Learn & practise', 'Focus on the knowledge and skills you really need.'), ('Track & adjust', 'Progress reviewed stage by stage, with content updated as your goals change.')],
  t_forms='Flexible formats',
  forms=[('One-to-one', 'All the time and content focused on one learner.'), ('Small group', 'Learn with friends, family or a group with the same goal.'), ('Online / Offline', 'Choose the format that fits your schedule and needs.')],
  t_faq='Frequently asked',
  faq=[('Can I learn online?', 'Yes. Content and delivery are adapted for online learning.'),
       ('Can I choose my teacher?', "SunMoon recommends a teacher based on the learner's age, level, goals and learning style."),
       ('Can the content change along the way?', 'Yes. The pathway is tracked and adjusted to actual progress.')],
  t_note='Your own pathway. Your own pace.',
  note="SunMoon advises on schedule and fees based on each learner's goals, level and format.",
  reg='Request advice / a trial lesson', ask='Message SunMoon on Zalo'),
 'zh': dict(
  kicker='按需定制 · Personalised Classes',
  tag=['为您量身设计的课程'],
  lead='不是每个人都需要同一条学习路径。<br>每个人的目标、基础和可用时间都不同。<br><br>日月根据每位学员的实际起点和目标设计课程——无论是速成口语、留学准备、工作需要，还是查漏补缺。',
  fit=['有自己学习目标的人：留学、工作、考试、口语……', '有具体需求、需要速成的人', '工作忙、需要灵活时间的人', '想专注某一项技能或主题的学员', '需要一对一辅导、巩固或补习的孩子'],
  out=[],
  t_how='每条路径都从您出发',
  steps=[('了解目标', '老师与您沟通，了解现有水平、需求和可用于学习的时间。'), ('设计路径', '内容、进度和教材按您的目标调整。'), ('学习与练习', '专注于您真正需要用到的知识和技能。'), ('跟进与调整', '分阶段评估进步，目标或需求变化时及时调整内容。')],
  t_forms='形式灵活',
  forms=[('一对一', '全部时间和内容只为一位学员。'), ('小组', '可以和朋友、家人或同目标的人一起学。'), ('线上 / 线下', '选择适合您时间和需求的上课方式。')],
  t_faq='常见问题',
  faq=[('可以线上学吗？', '可以。内容和授课方式会针对线上学习调整。'),
       ('可以选择老师吗？', '日月会根据学员的年龄、水平、目标和学习风格推荐老师。'),
       ('学习过程中可以调整内容吗？', '可以。学习路径会根据实际进度跟进并调整。')],
  t_note='专属路径，专属节奏。',
  note='上课时间与学费：日月会根据每位学员的目标、水平和上课形式为您介绍。',
  reg='预约咨询 / 试听', ask='Zalo 联系日月'),
},
'comm': {
 'adult': True,
 'vi': dict(
  kicker='Thiếu niên & người lớn · Conversational Chinese',
  tag=['Học để nói. Học để dùng.'],
  lead='Dành cho thiếu niên và người lớn muốn sử dụng tiếng Trung trong đời sống, du lịch, công việc và những cuộc trò chuyện thực tế.<br><br>Không đặt nặng việc học thuộc một giáo trình cố định. Mỗi buổi học tập trung vào nghe – hiểu – nói – phản xạ, để tiếng Trung dần trở thành một ngôn ngữ bạn có thể sử dụng tự nhiên.',
  t_out='Bạn sẽ dùng được gì?',
  out=['Làm quen với phát âm và thanh điệu chuẩn', 'Nghe hiểu và phản hồi trong những tình huống giao tiếp quen thuộc', 'Chào hỏi, giới thiệu bản thân, hỏi đường, mua sắm, gọi món', 'Trò chuyện về công việc, gia đình, sở thích và cuộc sống', 'Tăng tốc độ phản xạ khi nói', 'Tự tin hơn khi bắt đầu một cuộc hội thoại bằng tiếng Trung'],
  t_how='Mỗi buổi học',
  steps=[('Học qua tình huống', 'Từ vựng và mẫu câu xuất hiện trong những tình huống thực tế.'), ('Nghe & hiểu', 'Làm quen với cách người Trung Quốc sử dụng câu nói trong giao tiếp.'), ('Nói & phản xạ', 'Luyện theo cặp, nhóm nhỏ và các tình huống đóng vai.'), ('Sửa trực tiếp', 'Giáo viên sửa phát âm, thanh điệu và cách diễn đạt để bạn nói tự nhiên hơn.')],
  cls=[], t_cls='Lớp nhỏ — để ai cũng được nói',
  cls_text=['Không phải ngồi nghe giáo viên nói suốt buổi.', 'Lớp được tổ chức theo nhóm nhỏ để mỗi học viên có nhiều thời gian thực hành và được sửa trực tiếp.', 'Bạn có thể tham gia học thử trước khi đăng ký để xem cách học có phù hợp với mình hay không.'],
  t_faq='Bạn thường hỏi',
  faq=[('Tôi chỉ muốn giao tiếp, không cần học viết chữ Hán có được không?', 'Được. Nội dung có thể tập trung nhiều hơn vào nghe, nói, phát âm và phản xạ theo mục tiêu của bạn.'),
       ('Tôi đã quên gần hết tiếng Trung thì có học được không?', 'Có. Giáo viên sẽ đánh giá trình độ hiện tại và tư vấn lớp phù hợp, không nhất thiết phải bắt đầu lại từ đầu.'),
       ('Tôi chưa từng học tiếng Trung thì sao?', 'Bạn có thể bắt đầu từ lớp nền tảng, sau đó chuyển sang giao tiếp khi đã có đủ vốn từ và mẫu câu cơ bản.')],
  t_note='Tiếng Trung không chỉ để học.', note_lead='Mà để sử dụng trong cuộc sống.',
  note='Lịch học và học phí được SunMoon tư vấn theo độ tuổi, trình độ và mục tiêu giao tiếp của từng học viên.',
  reg='Đăng ký học thử'),
 'en': dict(
  kicker='Teens & adults · Conversational Chinese',
  tag=['Learn to speak. Learn to use it.'],
  lead='For teens and adults who want to use Chinese in daily life, travel, work and real conversations.<br><br>No heavy focus on memorising a fixed textbook. Each lesson centres on listening, understanding, speaking and reflexes, so Chinese gradually becomes a language you use naturally.',
  t_out='What will you be able to do?',
  out=['Get used to correct pronunciation and tones', 'Understand and respond in familiar situations', 'Greet people, introduce yourself, ask for directions, shop, order food', 'Talk about work, family, hobbies and daily life', 'Speak with faster reflexes', 'Feel more confident starting a conversation in Chinese'],
  t_how='Each lesson',
  steps=[('Learn through situations', 'Words and phrases come from real-life situations.'), ('Listen & understand', 'Get used to how Chinese people actually speak.'), ('Speak & react', 'Pair work, small groups and role-play.'), ('Instant correction', 'The teacher corrects pronunciation, tones and phrasing so you sound more natural.')],
  cls=[], t_cls='Small classes — so everyone gets to speak',
  cls_text=["You won't sit listening to the teacher all lesson.", 'Classes are small so each learner gets lots of practice and direct correction.', 'You can join a trial lesson first to see whether this way of learning suits you.'],
  t_faq='You often ask',
  faq=[("I only want to speak — do I have to learn characters?", 'No. The content can focus more on listening, speaking, pronunciation and reflexes, based on your goals.'),
       ("I've forgotten most of my Chinese. Can I still join?", "Yes. The teacher assesses your current level and suggests the right class — you don't necessarily start over."),
       ("I've never learnt Chinese. What then?", 'You can start with a foundation class, then move on to conversation once you have basic vocabulary and sentence patterns.')],
  t_note="Chinese isn't just for studying.", note_lead="It's for living.",
  note="SunMoon advises on schedule and fees based on each learner's age, level and speaking goals.",
  reg='Book a trial lesson'),
 'zh': dict(
  kicker='青少年与成人 · Conversational Chinese',
  tag=['学了就要说，学了就要用。'],
  lead='适合想在生活、旅行、工作和真实对话中使用中文的青少年与成人。<br><br>不强调死记固定教材，每节课聚焦听、懂、说和反应，让中文逐渐成为您能自然使用的语言。',
  t_out='您能用中文做什么？',
  out=['熟悉标准发音和声调', '在熟悉的交际情境中听懂并回应', '问候、自我介绍、问路、购物、点餐', '聊工作、家庭、爱好和生活', '提高口语反应速度', '更自信地用中文开启对话'],
  t_how='每节课',
  steps=[('情境学习', '词汇和句型来自真实情境。'), ('听与懂', '熟悉中国人在交流中的真实说法。'), ('说与反应', '两人练习、小组练习和角色扮演。'), ('当场纠正', '老师纠正发音、声调和表达，让您说得更自然。')],
  cls=[], t_cls='小班——人人都有机会开口',
  cls_text=['不用整节课坐着听老师讲。', '小组教学，每位学员都有充足的练习时间，并得到老师直接纠正。', '报名前可以先试听，看看这种学习方式是否适合您。'],
  t_faq='常见问题',
  faq=[('我只想学口语，不学写汉字可以吗？', '可以。内容可以根据您的目标更侧重听、说、发音和反应。'),
       ('我学过的中文几乎都忘了，还能学吗？', '可以。老师会评估您目前的水平并推荐合适的班级，不一定要从头开始。'),
       ('我从没学过中文怎么办？', '可以先从基础班开始，有了基本词汇和句型后再转入口语班。')],
  t_note='中文不只是用来学的，', note_lead='更是用来生活的。',
  note='上课时间与学费：日月会根据每位学员的年龄、水平和口语目标为您介绍。',
  reg='预约试听'),
},
'hsk': {
 'adult': True,
 'vi': dict(
  kicker='Thiếu niên & người lớn · HSK',
  tag=['Học có mục tiêu. Thi có lộ trình.'],
  lead='Dành cho thiếu niên và người lớn cần luyện thi HSK, chuẩn bị cho du học, học tập hoặc những mục tiêu công việc có yêu cầu về năng lực tiếng Trung.<br><br>SunMoon xây dựng lộ trình theo từng cấp độ, giúp học viên biết mình đang ở đâu, cần bổ sung gì và đang tiến bộ như thế nào.',
  fit=['Học viên cần chuẩn bị thi HSK 1–6', 'Người cần chứng chỉ phục vụ du học, học bổng hoặc hồ sơ học tập', 'Người muốn có một lộ trình học tiếng Trung rõ ràng và có cột mốc cụ thể', 'Học viên đã có nền tảng nhưng cần hệ thống lại kiến thức trước kỳ thi'],
  t_out='Bạn sẽ được chuẩn bị gì?',
  out=['Hệ thống hoá từ vựng và ngữ pháp theo từng cấp độ', 'Làm quen với cấu trúc và dạng bài của kỳ thi', 'Luyện từng kỹ năng: Nghe · Đọc · Viết', 'Thực hành với đề và bài tập theo thời gian quy định', 'Chữa bài, phân tích lỗi sai và xác định phần kiến thức cần cải thiện', 'Làm quen với áp lực thời gian trước khi bước vào kỳ thi thực tế'],
  t_how='Mỗi buổi học',
  steps=[('Kiến thức trọng tâm', 'Học và củng cố từ vựng, ngữ pháp theo cấp độ HSK.'), ('Luyện kỹ năng', 'Thực hành nghe, đọc, viết theo từng dạng bài.'), ('Làm bài', 'Luyện tập với cấu trúc và thời gian tương tự bài thi.'), ('Chữa & điều chỉnh', 'Giáo viên phân tích lỗi sai và hướng dẫn cách cải thiện.')],
  t_cls='Lớp nhỏ — học đúng trình độ',
  cls=['Học theo từng cấp độ', 'Kiểm tra trình độ đầu vào trước khi xếp lớp', 'Nhóm nhỏ để giáo viên có thể theo sát quá trình học', 'Có thể học thử trước khi đăng ký'],
  t_faq='Học viên thường hỏi',
  faq=[('Tôi nên bắt đầu từ HSK mấy?', 'Không nhất thiết phải chọn theo tuổi. SunMoon sẽ đánh giá nền tảng hiện tại để tư vấn cấp độ phù hợp.'),
       ('Tôi chưa học HSK bao giờ có học được không?', 'Có. Nếu chưa có nền tảng, bạn sẽ được tư vấn lộ trình xây nền trước khi bước vào luyện thi.'),
       ('SunMoon có luyện HSKK không?', 'Có thể tư vấn chương trình luyện HSKK theo nhu cầu và mục tiêu thi của học viên.')],
  t_note='Mỗi cấp độ là một cột mốc.', note_lead='HSK 1 → HSK 2 → HSK 3 → HSK 4 → HSK 5 → HSK 6',
  note='Không chỉ để vượt qua một kỳ thi, mà để từng bước xây dựng năng lực tiếng Trung có hệ thống.<br><br>Lịch học và học phí được SunMoon tư vấn theo trình độ hiện tại, cấp độ mục tiêu và thời gian dự kiến thi.',
  reg='Đăng ký kiểm tra trình độ / học thử'),
 'en': dict(
  kicker='Teens & adults · HSK',
  tag=['Study with a goal. Sit the exam with a plan.'],
  lead='For teens and adults preparing for HSK, study abroad, academic goals or jobs that require Chinese proficiency.<br><br>SunMoon builds a level-by-level pathway so learners know where they are, what they need and how they are progressing.',
  fit=['Learners preparing for HSK 1–6', 'Anyone who needs a certificate for study abroad, scholarships or applications', 'Anyone who wants a clear Chinese pathway with concrete milestones', 'Learners with some basics who need to consolidate before the exam'],
  t_out='How will you be prepared?',
  out=['Vocabulary and grammar organised by level', 'Familiarity with the exam structure and question types', 'Skill-by-skill practice: Listening · Reading · Writing', 'Practice tests under real time limits', 'Error review and analysis to target what needs improving', 'Getting used to time pressure before the real exam'],
  t_how='Each lesson',
  steps=[('Core knowledge', 'Learn and consolidate HSK vocabulary and grammar by level.'), ('Skill practice', 'Listening, reading and writing by question type.'), ('Test practice', 'Work with the same structure and timing as the exam.'), ('Review & adjust', 'The teacher analyses mistakes and shows how to improve.')],
  t_cls='Small classes — the right level',
  cls=['Classes by level', 'Placement check before joining a class', 'Small groups so the teacher can follow your progress', 'Trial lesson available before enrolling'],
  t_faq='Learners often ask',
  faq=[('Which HSK level should I start with?', "It doesn't depend on age. SunMoon assesses your current level and recommends the right one."),
       ("I've never studied HSK. Can I join?", "Yes. If you don't have a foundation yet, we'll suggest a foundation pathway before exam prep."),
       ('Do you prepare for HSKK?', 'We can advise on an HSKK programme based on your needs and exam goals.')],
  t_note='Every level is a milestone.', note_lead='HSK 1 → HSK 2 → HSK 3 → HSK 4 → HSK 5 → HSK 6',
  note='Not just to pass an exam, but to build your Chinese step by step, systematically.<br><br>SunMoon advises on schedule and fees based on your current level, target level and exam date.',
  reg='Book a level check / trial lesson'),
 'zh': dict(
  kicker='青少年与成人 · HSK',
  tag=['学习有目标，考试有路径。'],
  lead='适合需要备考 HSK、准备留学、学业或工作中对中文能力有要求的青少年与成人。<br><br>日月按级别设计学习路径，让学员清楚自己在哪里、需要补什么、进步了多少。',
  fit=['准备 HSK 1–6 级考试的学员', '需要证书用于留学、奖学金或申请材料的人', '希望有清晰中文学习路径和具体里程碑的人', '已有基础、考前需要系统梳理知识的学员'],
  t_out='您将获得哪些准备？',
  out=['按级别系统梳理词汇和语法', '熟悉考试结构和题型', '分技能练习：听力 · 阅读 · 书写', '按规定时间做题练习', '讲评试卷、分析错误，找出需要提升的部分', '考前适应时间压力'],
  t_how='每节课',
  steps=[('核心知识', '按 HSK 级别学习并巩固词汇和语法。'), ('技能练习', '按题型练习听、读、写。'), ('做题', '按与考试相同的结构和时间练习。'), ('讲评与调整', '老师分析错误并指导如何提高。')],
  t_cls='小班——按水平学习',
  cls=['按级别分班', '分班前进行入学水平测试', '小组教学，老师全程跟进', '报名前可先试听'],
  t_faq='学员常问',
  faq=[('我应该从 HSK 几级开始？', '不一定按年龄选。日月会评估您的现有基础，推荐合适的级别。'),
       ('我从没学过 HSK 可以吗？', '可以。如果还没有基础，我们会先建议打基础的学习路径，再进入备考。'),
       ('日月有 HSKK 辅导吗？', '可以根据学员的需求和考试目标，推荐 HSKK 辅导方案。')],
  t_note='每一级都是一个里程碑。', note_lead='HSK 1 → HSK 2 → HSK 3 → HSK 4 → HSK 5 → HSK 6',
  note='不只是为了通过一次考试，而是一步步系统地建立中文能力。<br><br>上课时间与学费：日月会根据您的现有水平、目标级别和预计考试时间为您介绍。',
  reg='预约水平测试 / 试听'),
},
'math': {
 'adult': False,
 'vi': dict(
  fit=['Bé <b>3–6 tuổi</b>', 'Chuẩn bị nền tư duy trước khi vào lớp 1'],
  out=['Hiểu <b>số và lượng</b>, không chỉ đếm thuộc lòng', 'Nhận biết <b>hình khối, quy luật</b>', 'Biết suy luận, giải câu đố đơn giản', 'Tập trung và kiên nhẫn hơn'],
  how=['Học bằng <b>đồ vật thật</b> và mô hình', 'Trò chơi tư duy, câu đố', 'Tình huống thực tế: chia kẹo, xếp hình…'],
  cls=['Lớp nhỏ, <b>tối đa 6 bé</b>', 'Ba mẹ nhận <b>nhận xét riêng</b> sau buổi học'],
  faq=[('Toán tư duy khác học toán ở trường thế nào?', 'Con học cách suy nghĩ qua đồ vật và trò chơi, không học thuộc bảng tính.')]),
 'en': dict(
  fit=['Children <b>aged 3–6</b>', 'Building thinking skills before primary school'],
  out=['Understand <b>numbers and quantity</b>, not just counting', 'Recognise <b>shapes and patterns</b>', 'Reason and solve simple puzzles', 'Better focus and patience'],
  how=['Learning with <b>real objects</b> and models', 'Logic games and puzzles', 'Real-life situations: sharing sweets, building shapes…'],
  cls=['Small groups, <b>max 6 children</b>', 'Parents receive <b>personal feedback</b> after lessons'],
  faq=[('How is this different from school maths?', 'Children learn how to think through objects and games, not by memorising tables.')]),
 'zh': dict(
  fit=['<b>3–6 岁</b>的孩子', '为上小学打好思维基础'],
  out=['理解<b>数与量</b>，而不只是背数', '认识<b>图形与规律</b>', '学会推理，解决简单谜题', '更专注、更有耐心'],
  how=['用<b>实物</b>和教具学习', '思维游戏与谜题', '生活情境：分糖果、拼图形……'],
  cls=['小班教学，<b>每班最多 6 名孩子</b>', '课后家长会收到<b>个人点评</b>'],
  faq=[('思维数学和学校数学有什么不同？', '孩子通过实物和游戏学会思考，而不是背算式。')]),
},
'writing': {
 'adult': False,
 'vi': dict(
  fit=['Bé <b>5–7 tuổi</b>', 'Chuẩn bị vào lớp 1 hoặc đang học lớp 1'],
  out=['<b>Cầm bút đúng</b>, ngồi đúng tư thế', 'Viết đúng <b>nét cơ bản</b>, chữ đều và sạch', 'Kiên nhẫn, cẩn thận hơn'],
  how=['Khởi động tay, tập tư thế ngồi', 'Luyện từng nét, từng chữ cùng cô', 'Khen và sửa riêng cho từng bé'],
  cls=['Lớp nhỏ, cô cầm tay sửa cho từng bé', 'Ba mẹ nhận <b>nhận xét riêng</b> sau buổi học'],
  faq=[('Con viết chữ tiếng Việt hay tiếng Trung?', 'Ba mẹ nhắn SunMoon để được tư vấn nội dung phù hợp với con.')]),
 'en': dict(
  fit=['Children <b>aged 5–7</b>', 'Getting ready for, or already in, Grade 1'],
  out=['<b>Correct pen grip</b> and sitting posture', 'Neat <b>basic strokes</b> and even handwriting', 'More patience and care'],
  how=['Hand warm-ups and posture practice', 'Stroke-by-stroke practice with the teacher', 'Individual praise and correction'],
  cls=['Small groups; the teacher guides each child by hand', 'Parents receive <b>personal feedback</b> after lessons'],
  faq=[('Vietnamese or Chinese handwriting?', 'Message SunMoon and we will suggest the right content for your child.')]),
 'zh': dict(
  fit=['<b>5–7 岁</b>的孩子', '准备上小学或正在读一年级'],
  out=['<b>正确握笔</b>，坐姿端正', '写好<b>基本笔画</b>，字迹工整', '更有耐心、更细心'],
  how=['手部热身，练习坐姿', '跟老师一笔一画练习', '老师逐一表扬与纠正'],
  cls=['小班，老师手把手指导', '课后家长会收到<b>个人点评</b>'],
  faq=[('练的是越南文还是中文书写？', '请联系日月，我们会根据孩子情况推荐合适内容。')]),
},
'camp': {
 'adult': False,
 'vi': dict(
  fit=['Các bé muốn <b>trải nghiệm</b> trong kỳ nghỉ hè, đông, xuân', 'Bé chưa học hoặc đã học tiếng Trung đều tham gia được'],
  out=['Dùng tiếng Trung qua <b>hoạt động thật</b>', 'Hiểu thêm <b>văn hoá Trung Hoa</b>', 'Kết bạn, tự tin làm việc nhóm'],
  how=['Mỗi ngày một chủ đề', 'Trò chơi, thủ công, nấu ăn, biểu diễn…', 'Tổng kết, ba mẹ xem lại hoạt động của con'],
  cls=['Khoá ngắn theo mùa', 'Lịch và nội dung <b>thông báo trước khi mở đăng ký</b>'],
  faq=[('Khi nào có Camp?', 'SunMoon thông báo trên Fanpage và Zalo trước mỗi mùa. Ba mẹ nhắn để được báo sớm.')]),
 'en': dict(
  fit=['Children who want a <b>holiday experience</b> in summer, winter or spring', 'Open to beginners and children already learning Chinese'],
  out=['Use Chinese through <b>real activities</b>', 'Learn more about <b>Chinese culture</b>', 'Make friends and grow confident in teams'],
  how=['A new theme each day', 'Games, crafts, cooking, performances…', 'A wrap-up so parents can see what their child did'],
  cls=['Short seasonal programmes', 'Dates and content <b>announced before registration opens</b>'],
  faq=[('When are the camps?', 'SunMoon announces them on Facebook and Zalo before each season. Message us to hear first.')]),
 'zh': dict(
  fit=['想在暑假、寒假、春假<b>体验</b>学习的孩子', '零基础或已学过中文的孩子都可参加'],
  out=['在<b>真实活动</b>中使用中文', '了解<b>中华文化</b>', '结交朋友，学会团队合作'],
  how=['每天一个主题', '游戏、手工、烹饪、表演……', '结营展示，家长可看到孩子的成果'],
  cls=['按季节开设的短期营', '时间和内容<b>在开放报名前公布</b>'],
  faq=[('什么时候有营地课程？', '每季开营前会在 Facebook 和 Zalo 公布，欢迎留言提前获取通知。')]),
},
}
